happy-geeks/wiser

- Api/Core/Queries/WiserInstallation/InsertInitialDataEcommerce.sql
Added query to the InsertInitialDataEcommerce query that sets a default
link between basket and basketline to ensure the parent_item_id column
is used instead of wiser_itemlink.
> Default basketline link

- FrontEnd/Modules/Templates/Css/Templates.css
- FrontEnd/Modules/Templates/Views/Templates/Partials/HtmlSettings.cshtml
In de template-module is het query-veld (in het advanced-panel) onder de overige velden geplaatst, 100% breed.
> Templates module - query preview placement adjusted

- Api/Modules/Items/FieldTemplates/HTMLeditor.html
- FrontEnd/Modules/DynamicItems/Scripts/Fields.js
When saving an item, it would always save the original value again.
> Fixed bug in HTML editor

- FrontEnd/Core/Models/FrontEndSettings.cs
- FrontEnd/Modules/TaskAlerts/Scripts/TaskAlerts.js
- FrontEnd/Modules/TaskAlerts/Views/TaskAlerts/Index.cshtml
The app key for Pusher was hard-coded in the TaskAlerts scripting. The key has been moved to the appsettings.
> Removed hard-coded app key for Pusher

- Api/Modules/Customers/Services/UsersService.cs
When an user has been blocked and requests a new password using the "Forgot password" functionality the account kept blocked and the new password was useless. This is now being reset.
https://app.asana.com/0/1201027711166952/1202847033936390
> Reset login attempts after forgot password.

- FrontEnd/Modules/Base/Css/kendo.wiser.css
Na een update van Kendo UI ging het op enkele plekken mis met het tonen van de juiste icons in buttons.
> Missing icons in buttons corrected

- Api/Modules/Templates/Services/TemplatesService.cs
The "linked-item" fields didn't work anymore due to a mismatch in the field name that contains the entity type.
https://app.asana.com/0/1144661858028300/1202928183224518
> Fixed "linked-item" not working anymore

- FrontEnd/Modules/DataSelector/Scripts/DataLoad.js
- FrontEnd/Modules/DataSelector/Scripts/DataSelector.js
- FrontEnd/Modules/DataSelector/Views/DataSelector/Index.cshtml
Fields in the data selector now supports selecting multiple language codes.
Accompanying PR for GCL: https://github.com/happy-geeks/geeks-core-library/pull/197
https://app.asana.com/0/1201027711166952/1202597780412822
> Data selector multilingual field support

- FrontEnd/Modules/Templates/Scripts/Templates.js
The new default name of the folder for service configurations is "SERVICES" instead of "AIS", but since there was no property for "SERVICES", the template type for new configurations would be 0 instead of 8.
> Added "SERVICES" to template types

- Api/Modules/Grids/Services/GridsService.cs
De agendering historie wou niet laden vanwege een error. Hierin ging het fout bij de ORDER BY clause.
De dueDate kon niet gevonden worden vanwege een verkeerde spelling. Bij deze is dat opgelost
Asana ticket:
https://app.asana.com/0/1201027711166952/1203158028215064
> Fixed error that agendering history wouldnt load

- FrontEnd/Core/Scripts/main.js
De cache URL wordt nu ingevuld in het cache URL veld indien er een cache URL in de localstorage staat.
Asana ticket: https://app.asana.com/0/1201027711166952/1203158028215056
> Cache URL will now be stored in localstorage

- FrontEnd/Modules/ImportExport/Scripts/Import.js
Value in property is a boolean. parseInt always returned "NaN' causing the statement to be always false.
https://app.asana.com/0/1201027711166952/1202687945925209
> Fix image upload.

- Api/Modules/Templates/Models/Template/TemplateSettingsModel.cs
- Api/Modules/Templates/Services/DataLayer/HistoryDataService.cs
- Api/Modules/Templates/Services/DataLayer/TemplateDataService.cs
- Api/Modules/Templates/Services/HistoryService.cs
- FrontEnd/Modules/Templates/Views/Templates/Partials/HtmlSettings.cshtml
Add functionality to mark an HTML template as a partial to ignore the header and footer template when requesting a template through an XHR call. Templates marked as partial no longer need to use "ombouw=false".
Combined with GCL pull request: https://github.com/happy-geeks/geeks-core-library/pull/242
https://app.asana.com/0/1200346761113317/1203257614129593/
> Add settings to mark a HTML template as a partial.

- Api/Modules/Pusher/Models/PusherMessageRequestModel.cs
- Api/Modules/Pusher/Services/PusherService.cs
- FrontEnd/Modules/DynamicItems/Scripts/Fields.js
- FrontEnd/Modules/TaskAlerts/Scripts/TaskAlerts.js
- FrontEnd/Modules/Templates/Scripts/TemplateConnectedUsers.js
Changed the way Pusher works so the channel names and event names can actually be used the way they were intended to be used. This allows the `TemplateConnectedUsers` scripting to create a channel specific for the current sub-domain. Also changes some scripting in `TaskAlerts` and `Fields` so they don't break due to the Pusher changes.
Asana: https://app.asana.com/0/1201027711166952/1203521973607618
> Pusher changes for template connected users

- Api/Core/Helpers/IdentityHelpers.cs
- Api/Core/Queries/WiserInstallation/CreateDedicatedItemTablesTriggers.sql
- Api/Core/Queries/WiserInstallation/CreateTriggers.sql
- Api/Core/Services/ApiReplacementsService.cs
- Api/Modules/Files/Interfaces/IFilesService.cs
- Api/Modules/Files/Services/FilesService.cs
- Api/Modules/Grids/Services/GridsService.cs
- Api/Modules/Imports/Services/ImportsService.cs
- Api/Modules/Items/Services/ItemsService.cs
- Api/Modules/Modules/Services/ModulesService.cs
- Api/Modules/Templates/Services/HistoryService.cs
- FrontEnd/Modules/Admin/Scripts/Admin.js
- FrontEnd/Modules/Communication/Scripts/Index.js
- FrontEnd/Modules/Communication/Scripts/Settings.js
- FrontEnd/Modules/Dashboard/Scripts/Dashboard.js
- FrontEnd/Modules/DataSelector/Scripts/DataSelector.js
- FrontEnd/Modules/DynamicItems/Scripts/DynamicItems.js
- FrontEnd/Modules/ImportExport/Scripts/Export.js
- FrontEnd/Modules/ImportExport/Scripts/Import.js
- FrontEnd/Modules/TaskAlerts/Scripts/TaskAlerts.js
- FrontEnd/Modules/TaskAlerts/Scripts/TaskHistory.js
- FrontEnd/Modules/Templates/Scripts/DynamicContent.js
- FrontEnd/Modules/Templates/Scripts/Templates.js
- FrontEnd/Modules/VersionControl/Scripts/VersionControl.js
When the admin user makes changes in Wiser, it would always show the username in history of the user they selected during login. This is changes so that it will now always show their admin username in history.
Also changed username in scripts where it would use "Happy Horizon ([username])", but Happy Horizon is not applicable for external users that use Wiser.
Finally, I also fixed some problems that changes made to files would show the MySQL user in the history, instead of the Wiser user.
Asana ticket: https://app.asana.com/0/1201027711166952/1203205263979130
> Show admin username in history

- Api/Core/Queries/WiserInstallation/CreateTables.sql
- FrontEnd/Modules/Templates/Views/Templates/Partials/HtmlSettings.cshtml
"is_partial" column will now be added to the table during creation of a new customer.
https://app.asana.com/0/1201027711166952/1203654426049449/
The option in the settings is moved to a more logical location. (Git says "loginRequired" has changed because the "isPartial" is moved from under to above "loginRequired".)
https://app.asana.com/0/1201027711166952/1203601461297517/
> Add is_partial to initial creation of tables and move location in Wiser.

- FrontEnd/Modules/Templates/Scripts/Templates.js
When a template was saved it's published environment stayed 0 (hidden) instead of 1 (development).
After saving it will now be deployed making sure the latest version is seen as deployed to development instead the last version that was deployed to test or higher.
Together with: https://github.com/happy-geeks/wiser-task-scheduler/pull/27
https://app.asana.com/0/7257459017111/1203426290923318
> Deploy a template to development when saved.

- FrontEnd/Core/Scripts/main.js
Two new post message actions have been added:
* `OpenItem`: Will open a Wiser item with the specified data.
* `GetAccessToken`: Will respond to the source window with the access token. Will refresh if needed. Note: This will only work on test environments, and for iframes that are loaded in the same main domain.
Asana: https://app.asana.com/0/1182779092805226/1201031439734820
> Added new post message actions

- Api/Modules/Items/FieldTemplates/sub-entities-grid.js
A grid with incell editing enabled can now properly save values again. It didn't work previously because it couldn't determine an item's encrypted ID.
Asana: https://app.asana.com/0/1201763244049195/1203837014778910
> Fixed grid incell editing

- Api/Modules/Items/Controllers/ItemsController.cs
- Api/Modules/Items/FieldTemplates/linked-item.js
- Api/Modules/Items/Interfaces/IItemsService.cs
- Api/Modules/Items/Services/ItemsService.cs
- Api/Modules/Templates/Services/TemplatesService.cs
Made some changes to the linked-item properties:
* Now uses the newly made linked details endpoint in the items controller.
* The new linked details endpoint retrieves all details instead of only those defined in the entity properties.
* Added new option to remove unknown variables (`removeUnknownVariables`).
* Updated the scripts a bit to use modern functions.
* Removed the "GET_DESTINATION_ITEMS" and "GET_DESTINATION_ITEMS_REVERSED" queries from the templates service.
Asana: https://app.asana.com/0/1201027711166952/1203351288497689
> Changes for linked-item properties

- Api/Modules/Templates/Services/TemplatesService.cs
https://app.asana.com/0/0/1203089430259003/f
In de beheer scherm bij de dropdown voor veld afhankelijkheden zijn de velden duidelijker gemaakt door de tabnaam erbij te zetten. Dit is hetzelfde idee als al bij de Entiteiten is gedaan. De gebruikte format is dan ook hetzelfde. 
Bijvoorbeeld "Gegevens --> Product naam"
> Disambiguate fieldnames

- Api/Modules/VersionControl/Controllers/VersionControlController.cs
- Api/Modules/VersionControl/Interfaces/ICommitService.cs
- Api/Modules/VersionControl/Models/DeployCommitsRequestModel.cs
- Api/Modules/VersionControl/Services/CommitService.cs
- FrontEnd/Modules/VersionControl/Scripts/VersionControl.js
* Fixed bug that commits were deployed in the wrong order and therefor eventually have the wrong version deployed to the selected environment.
* Improved performance of deploying several commits at once by committing only the highest version of each template/component, instead of all one by one.
* This change also gives a much clearer historie in the deployed templates/components.
Asana ticket: https://app.asana.com/0/1201027711166952/1203770707149963
> Refactored code for deploying commits, to make it more efficient and to fix a bug.

- FrontEnd/Modules/Admin/Scripts/EntityTab.js
- FrontEnd/Modules/DynamicItems/Scripts/Fields.js
When the value is set directly instead of by a replacement it can be an integer causing an exception to be thrown on the replace function.
By always parsing it to a string the replace function can be called. If the value was already a string it did already return as a string.
https://app.asana.com/0/1144661858028300/1204522191718286
> Always parse value to string

- Api/Api.csproj
- Api/Modules/Files/Models/TinyPngSettings.cs
- Api/Modules/Files/Services/FilesService.cs
- Api/Startup.cs
https://app.asana.com/0/1201027711166952/1204477365701444/f
Adds support for tinyPNG during upload.
Api key should be added by with `TinifyApiKey` in an `TinyPNG` section
App settings example:
`
"TinyPNG": {
"TinifyApiKey": "YOUR_KEY_HERE"
}
`
> Add TinyPNG support

- Api/Modules/Templates/Controllers/DynamicContentController.cs
- Api/Modules/Templates/Controllers/TemplatesController.cs
- Api/Modules/Templates/Interfaces/DataLayer/IDynamicContentDataService.cs
- Api/Modules/Templates/Interfaces/DataLayer/ITemplateDataService.cs
- Api/Modules/Templates/Interfaces/IDynamicContentService.cs
- Api/Modules/Templates/Interfaces/ITemplatesService.cs
- Api/Modules/Templates/Models/Other/Constants.cs
- Api/Modules/Templates/Services/CachedTemplatesService.cs
- Api/Modules/Templates/Services/DataLayer/DynamicContentDataService.cs
- Api/Modules/Templates/Services/DataLayer/TemplateDataService.cs
- Api/Modules/Templates/Services/DynamicContentService.cs
- Api/Modules/Templates/Services/HistoryService.cs
- Api/Modules/Templates/Services/TemplatesService.cs
- Api/Modules/VersionControl/Services/CommitService.cs
- Api/Modules/VersionControl/Services/DataLayer/CommitDataService.cs
- FrontEnd/Modules/Templates/Scripts/DynamicContent.js
- FrontEnd/Modules/Templates/Scripts/Templates.js
- FrontEnd/Modules/Templates/Views/DynamicContent/Partials/PublishedEnvironments.cshtml
- FrontEnd/Modules/Templates/Views/Templates/Partials/PublishedEnvironments.cshtml
- FrontEnd/Modules/VersionControl/Scripts/VersionControl.js
From now on, we will no longer create a new version for every update. When you save a template or component, it will now overwrite the latest version (as long as it's not published to live). When committing a template or component, that will automatically create a new version to work in from then on.
Asana ticket: https://app.asana.com/0/1201027711166952/1204878810711516
> Changes how the templates module works with versions

- Api/Core/Queries/WiserInstallation/InsertInitialDataConfigurator.sql
The example configurator tried to get the JavaScript folder using the old name "SCRIPTS" causing it to not find a result and place the new folder in the root.
https://app.asana.com/0/1201027711166952/1204913452394948
> Set correct name for JS folder within Wiser.

- Api/Modules/Items/FieldTemplates/linked-item.js
https://app.asana.com/0/1144661858028300/1204655574479297/f
Fixes a bug causing the closing bracket of replacements to show in wiser properties of type linked item
For example the template `{orderId} - {title}` would be replaced as `123} - awesome product}` instead of `123 - awesome product`
> Fix closing bracket being shown in link-item

- FrontEnd/Core/Scripts/main.js
The wrong object was used and casued a type error because the object was undefined prevent people form openening branches through Wiser.
https://app.asana.com/0/1205090868730163/1205266188687588
> Use the correct object to read the website URL from.

- Api/Modules/Templates/Services/DataLayer/TemplateDataService.cs
The reading connection was used. If a new version was added in a transaction this function would return the old version.
This went wrong when committing a template directly to live a new version was created for live and then again. Now the writing connection is used the transaction is recognized when getting the latest version.
https://app.asana.com/0/1205090868730163/1205158165975146
> Use writing connection when getting latest version number.

- Api/Core/Helpers/TypeHelpers.cs
- Api/Core/Interfaces/IPluginsService.cs
- Api/Core/Models/ApiSettings.cs
- Api/Core/Services/PluginsService.cs
- Api/Startup.cs
- Api/appsettings.Development.json
- FrontEnd/Core/Models/FrontEndSettings.cs
- FrontEnd/Modules/Templates/Controllers/DynamicContentController.cs
- FrontEnd/Startup.cs
- FrontEnd/appsettings.Development.json
We have split the GCL into multiple smaller libraries. For example, the configurator is now a separate library and no longer part of the base GCL library. To still be able to use and config configurators in Wiser, we need to be able to load plugins dynamically.
Asana ticket: https://app.asana.com/0/1205090868730163/1205074310342800
> Functionality for loading GCL/Wiser plugins

- FrontEnd/Modules/Admin/Scripts/EntityTab.js
After creating a new entity, the entities dropdown box did not select the new item.
The "databound" handler makes no sense if the code is waiting for the reloadEntityList to finish. The binding is done at this point, so simply select the new item.
---
- https://app.asana.com/0/0/1205300519905989
> Select new entity after creation

- FrontEnd/Modules/Admin/Scripts/EntityTab.js
When the command column in the grid is too narrow, the delete button gets clipped and ellipses are placed. However, the icon remains making it look broken. This change widens the window, giving enough room for each column, and removes the text from the delete button to have it use less room.
---
- https://app.asana.com/0/0/1205184957053785
> Fixed action button query parameter grid row delete button clipped off

- Api/Modules/Files/Services/Repository/FilesRepository.cs
at one of our costumer this caused the image viewer to return a error and not open, this convert was already present for the id itself so now is also added to the item id, this resolved the issue.
asana:
https://app.asana.com/0/1201394730777422/1205352004770791/f
> add a convert for itemId field in FilesRepository

- FrontEnd/Modules/Admin/Scripts/EntityTab.js
1. The crash happened in selectTabInTreeView which was inside the try-except scope, producing the incorrect add/remove failed error message.
2. Code is trying to open non-existing tabs in the treeview. It should try to open the default tree folder if tabName is empty.
3. Made selectTabInTreeView more defensive because it is possible the provided tab no longer exists (when the last property is deleted for example)
---
- https://app.asana.com/0/0/1205322186023693
> Incorrect error message on property add/delete

- Api/Modules/Items/FieldTemplates/sub-entities-grid.js
- FrontEnd/Modules/DynamicItems/Scripts/Grids.js
The filter event (now) only contains the new filter state, not the existing ones. So to save the correct state I need to merge the new filter with the current grid filters. Also made sure the filter event is triggered when the filters are reset.
---
- https://app.asana.com/0/0/1205063613165510
> Fixed saving filter state of entitiesgrid

- FrontEnd/Modules/Admin/Scripts/EntityTab.js
- FrontEnd/Modules/Dashboard/Scripts/Dashboard.js
- FrontEnd/Modules/DataSelector/Scripts/DataSelector.js
- FrontEnd/Modules/Templates/Scripts/Templates.js
Some grids had buttons with only text, some buttons had only an icon and some buttons had an icon and text.
Because https://app.asana.com/0/1201027711166952/1204420385110393 requested tooltips for some buttons with only icons I made ALL the grid buttons icon-only with tooltips.
> Made all grid buttons icons with a tooltip

- FrontEnd/Core/Views/Home/Index.cshtml
Added text with the name of the related module. If item has no related module, Module  #ModuleId will be shown instead.
Did not change order of items shown - still based on items, not on module name.
Ticket: https://app.asana.com/0/1201027711166952/1205666113042076/f
> Add label of module name to branch creation popup ( if no module nameis available module + moduleId will be shown instead)

- Api/Modules/Modules/Services/ModulesService.cs
- FrontEnd/Modules/Admin/Scripts/ModuleTab.js
- FrontEnd/Modules/Admin/Views/Admin/Index.cshtml
- FrontEnd/package.json
Removed possibility of updating the module ID. Also added a watch command reference to the package.json for easier use.
Ticket: https://app.asana.com/0/1201027711166952/1203115791838029/f
Screenshot below is changed view; moduleID inputfield has been changed to a label.
> Disable updating moduleId in Wiser configuration - add watch command for easier use

- Api/Modules/Templates/Models/History/HistoryVersionModel.cs
- Api/Modules/Templates/Models/History/TemplateHistoryModel.cs
- Api/Modules/Templates/Services/DataLayer/HistoryDataService.cs
- Api/Modules/Templates/Services/HistoryService.cs
- FrontEnd/Modules/Base/Css/diff2html.custom.css
- FrontEnd/Modules/Base/Scss/base.scss
- FrontEnd/Modules/Templates/Css/DynamicContent.css
- FrontEnd/Modules/Templates/Css/Templates.css
- FrontEnd/Modules/Templates/Scripts/DynamicContent.js
- FrontEnd/Modules/Templates/Scripts/Templates.js
- FrontEnd/Modules/Templates/Views/DynamicContent/Partials/DynamicContentHistoryRows.cshtml
- FrontEnd/Modules/Templates/Views/DynamicContent/Partials/HistoryInputGenerator.cshtml
- FrontEnd/Modules/Templates/Views/Templates/Partials/HistoryTabRows.cshtml
- FrontEnd/package-lock.json
- FrontEnd/package.json
Added JS to render Diff2Html fields instead of the big text areas (for HTML, queries, etc) in the Template and Dynamic Content history tabs. Adjusted the way the HTML is generated for those tabs to simplify the JS code.
---
- https://app.asana.com/0/0/1205766552804799
> Replaced text fields in Template histories with actual diff fields

- FrontEnd/Modules/DynamicItems/Scripts/DynamicItems.js
- FrontEnd/Modules/DynamicItems/Scripts/Windows.js
Kendo has built in formats for validation errors.
In this case the format was '{0} is not correct' where {0} is the name of the attribute, which is a non-friendly naming. 
I have added custom validation for the attributes which use the name of the attribute as parameter and take the label text instead. 
Ticket:  https://app.asana.com/0/1201027711166952/1205957824190022/f
> Add friendly validation message for pattern and step

- FrontEnd/Modules/Base/Scripts/Utils.js
- FrontEnd/Modules/DynamicItems/Scripts/Fields.js
When downloading or e-mailing files via Wiser, we can have variables in the file name. We now remove those variables from the file name, if we can't find a property for them.
Asana ticket: https://app.asana.com/0/1182779092805226/1204636198695342
> Remove unknown variables from file names

- FrontEnd/Core/Views/Home/Index.cshtml
Dialogs 'wiserIdPrompt' and 'wiserEntityTypePrompt' were defined twice, removed double define.
Changed mismatched property name that caused the actual bug.
https://app.asana.com/0/1201027711166952/1205759830564446
> Fixed entity type selection box being empty

- Api/Modules/Items/FieldTemplates/sub-entities-grid.js
- FrontEnd/Modules/DynamicItems/Scripts/Grids.js
Not having the counterContainer div means there is nothing pushing the buttons to the right side of the toolbar. Adding the div but keeping it empty is the most stable way of achieving the desired outcome.
https://app.asana.com/0/1201027711166952/1205657687817938
> subgrid toolbar whitespace when count is hidden is wrong

- Api/Modules/Items/Services/ItemsService.cs
I a sub entity grid (or grid) is used and the entity to be added must be connected via the parent_item_id of wiser_item this did not work. There was still a link added to the wiser_itemlink table and the parent_item_id was still set to 0 for the new item. This behaviour is fixed in this release.
> bugfix: parent_id is not ued when adding items with a subentity grid

- Api/Modules/VersionControl/Services/CommitService.cs
If a commit contains multiple templates/dynamic contents from which a template was published to a higher environment in another commit it would be published to the lowe version if the first commit is published.
This checks validates if the template is allowed to be published to the environment to ensure it can only go up.
https://app.asana.com/0/1201027711166952/1205193967551387
> Prevent lower versions from being published in the version control.

- FrontEnd/Modules/Templates/Scripts/DynamicContent.js
Changed number formatting for all dynamic content numeric fields to be a plain number, without a thousands separator.
https://app.asana.com/0/1201027711166952/1206116303028431
> Removed thousands separator in numeric fields

- Api/Modules/Templates/Controllers/TemplatesController.cs
- Api/Modules/Templates/Interfaces/DataLayer/ITemplateDataService.cs
- Api/Modules/Templates/Interfaces/ITemplatesService.cs
- Api/Modules/Templates/Services/CachedTemplatesService.cs
- Api/Modules/Templates/Services/DataLayer/TemplateDataService.cs
- Api/Modules/Templates/Services/TemplatesService.cs
- FrontEnd/Modules/Templates/Scripts/Templates.js
- FrontEnd/Modules/Templates/Views/Templates/Index.cshtml
- FrontEnd/Modules/Templates/Views/Templates/Tabs/DevelopmentTab.cshtml
This adds a button to the Template module that can be used to import data from a Wiser 1 templatemodule. This will then convert most components, replacements etc to the new syntax for the GCL and Wiser 3. This will not give you a 100% working website in most cases, it still requires some manual work after doing the import, but it saves most of the work.
Asana ticket: https://app.asana.com/0/1205090868730163/1201855300969674
> Wiser 1 to Wiser 3 templatemodule

- Api/Core/Queries/WiserInstallation/CreateTables.sql
- Api/Core/Queries/WiserInstallation/CreateTablesConfigurator.sql
The MySQL installations queries have been updated so they also create some additional columns in `wiser_itemdetail` and `wiser_itemlinkdetail`: `value_as_int` and `value_as_decimal`. These virtual columns will automatically convert the value column to an int and decimal value respectively.
Related GCL pull request: https://github.com/happy-geeks/geeks-core-library/pull/515
Asana:
https://app.asana.com/0/29553867016121/1203457154031219
https://app.asana.com/0/29553867016121/1202994198179349
> Updated MySQL installation queries

- FrontEnd/Modules/Admin/Scripts/EntityTab.js
The selectedEntityName was undefined so SQL queries returned 0 results. The property needed was actually called entityType.
Fixes both:
https://app.asana.com/0/1205090868730163/1205837166648269
and the groupbox part of
https://app.asana.com/0/1205090868730163/1205837166648264
> Admin module - Entity tab - Fix for group combobox and dependency dropdownbox

- Api/Modules/VersionControl/Services/DataLayer/CommitDataService.cs
When a template or dynamic content had multiple versions that were dirty, for example if the dropdown was used to publish it, the name of the first user was used. Now the name of the user that last worked on the template/dynamic content will be shown.
https://app.asana.com/0/1205090868730163/1206619984858606
> Use the correct user for the last updated column

- Api/Modules/Items/Controllers/ItemsController.cs
- Api/Modules/Items/Interfaces/IItemsService.cs
- Api/Modules/Items/Services/ItemsService.cs
- Title has been added to filter on
- More information is passed to next/previous URLs
- Possibility to disable use of property friendly name. When a friendly name was reused (within groups/tabs) within the entity the JSON gave an error due to duplicate keys
https://app.asana.com/0/1204297502076149/1206449896411068
> Improve the endpoint to get Wiser items from API

- Api/Modules/Templates/Services/DataLayer/TemplateDataService.cs
- Api/Modules/VersionControl/Models/DynamicContentCommitModel.cs
- Api/Modules/VersionControl/Models/TemplateCommitModel.cs
- Api/Modules/VersionControl/Services/DataLayer/CommitDataService.cs
- FrontEnd/Modules/VersionControl/Scripts/VersionControl.js
* You can now clearly see if a template has been deleted when you're committing or reviewing.
* Fixed bug in query that caused it to sometimes have 1 result with null in all columns.
* When doing a review and opening the changes for a component, you will now only see the changes of that component, instead of all changes of the template that the component is linked to.
* Fixed problem that loader was hidden too early, before we were done loading everything.
There is no Asana ticket for this. I made these changes when making a presentation to present this functionality.
> Some improvements to code review functionality of the version control / template module

- Api/Modules/Files/Services/FilesService.cs
Remove code to skip decrypting if a plain ID has been provided. Files are only allowed to be downloaded when using encrypted IDs.
https://app.asana.com/0/1205090868730163/1205887586007820
> Prevent file download from unencrypted item IDs

- Api/Modules/Queries/Services/QueriesService.cs
If the query resutls are retrieved in JSON as key-value pair it will give an error that the columns are missing instead of an object reference exception.
https://app.asana.com/0/1205090868730163/1204870251660089
> Give error when column are missing.

- FrontEnd/Modules/DynamicItems/Scripts/Fields.js
Arrays are now handled properly for the depends-on functionality (the value of a multiselect is an array of values). Also fixed the depends-on functionality being triggered twice for multiselects due to the inner input also triggering it.
[Asana ticket](https://app.asana.com/0/1144661858028300/1206215550582217)
> Fixes for depends-on functionality for multiselect

- Api/Modules/Templates/Services/DynamicContentService.cs
- Api/Modules/Templates/Services/TemplatesService.cs
When a template or dynamic content was deployed using the dropdowns no new version was created. When committing to the same environment the check to create a new version would fail because the latest version was already on that environment.
This check is now always executed for templates, instead of only for live. For dynamic contents this has been added since it was missing in the first place.
https://app.asana.com/0/1205090868730163/1206632507560566
> Fix missing versions when using dropdown to deploy

- Api/Core/Queries/WiserInstallation/CreateTriggers.sql
The create script contains a syntax error where there are two `BEGIN` statements with only one `END` statement.
I encountered this problem when I first installed Wiser locally. I removed the second `BEGIN` statement. This solved the issue and the script ran as expected.
_N/A_
_N/A_
> Fixed a syntax error of a duplicate BEGIN statement

- Api/Modules/Templates/Helpers/TemplateHelpers.cs
- Api/Modules/Templates/Services/DataLayer/TemplateDataService.cs
Fixed the loading of the widget content and widget location in templates.
Tested this with a template that had widget content and location set and confirmed that both settings were loaded after loading the template. Also confirmed that templates without those settings will still load properly.
N/A
No Asana ticket, ran into this while working with widget content.
> Fix for loading widget settings

- FrontEnd/Modules/Templates/Scripts/Templates.js
- FrontEnd/Modules/Templates/Views/Templates/Tabs/DevelopmentTab.cshtml
Added close button to template development tab that unloads the current template and enables the add button.
Local build tested locally with all template types.
none
https://app.asana.com/0/1201027711166952/1205948424661382
> Added close button to template development tab

- Api/Modules/Templates/Helpers/TemplateHelpers.cs
Trying to deploy a MySQL routine resulted in an error because the routine properties never got set. The `DataRowToTemplateSettingsModel` method has been updated so the routine properties get set, but only if the supplied `DataRow` actually has the required columns.
Used a debug build and tested the deploy functionality for a `FUNCTION` routine and confirmed that it now works as intended.
N/A
[Asana ticket](https://app.asana.com/0/1201027711166952/1207299005229571)
> Fixed deploying MySQL routines

- Api/Modules/Items/FieldTemplates/HTMLeditor.js
Incorrect if-statement made HTML editors ignore the "mode" setting if no manual tools options were set.
Local build, tested with and without manual additional tools on wiserdemo test entity
none
https://app.asana.com/0/1205090868730163/1207494284865152
> Fixed HTML editors always having all tools

- FrontEnd/Modules/Base/Scripts/Utils.js
Added button to view the entire contents of the template field in the diff sections of the template history tab. This opens a temporary kendo window containing another diff field.
Local build, works great with big and small template sources.
none
https://app.asana.com/0/1205090868730163/1206889839994812
> Added "view entire source" in template history diff fields

- FrontEnd/Modules/Templates/Scripts/DynamicContent.js
Initialisation of the kendo dropdowns in dynamic content got accidentally removed at some point. Because of this dropdowns like for example those for CachingMode and CachingLocation didn't work.
Please describe how you tested your changes and how you confirmed this functionality is not a breaking change.
N/A
https://app.asana.com/0/1205090868730163/1207674679626299/f
> Adds back kendo dropdown initialization

- Api/Core/Queries/WiserInstallation/InsertInitialDataConfigurator.sql
Fixed issue that added_on and added_by did not contain a value for new tenants in the examples for configurators.
I tested this by executing the updated queries in a test database.
N/A
https://app.asana.com/0/1205090868730163/1207527885769049
> Fixed issue that added_on and added_by did not contain a value for new tenants in the examples for configurators.

- Api/Modules/Items/Services/ItemsService.cs
When items of an entity are requested that have no properties an empty property would be given that failed to be processed. This skips that key.
Tested by requesting an entity type that has no properties and one that does.
N/A
https://app.asana.com/0/1199995500457439/1205916497751759/
> Fix get items endpoint when item has no properties

- Api/Modules/Branches/Interfaces/IBranchesService.cs
- Api/Modules/Branches/Services/BranchesService.cs
- Api/Modules/Files/Services/FilesService.cs
- Api/Modules/Items/Services/ItemsService.cs
- FrontEnd/Modules/FileManager/Scripts/FileManager.js
When a file is uploaded through the file manager (global files) when the user is on a branch the file will be saved to the branch and main database under the same ID. This ensures after a merge all references are correctly and allows the preview to retrieve the image from the main website. The same applies for directories for the file manager module in Wiser.
Refactored some parts to reduce duplicate code.
Tested by uploading images/files on the branch database in the file manager to see if they were created in both. Tested if the file was only saved in the main when uploaded there. And tested if an image for a Wiser item on a branch is only saved in the branch database.
N/A
CON-280
> Save files in branch and main database when uploading to file manager on branch

- FrontEnd/Modules/Templates/Scripts/Templates.js
Some templates are "virtual" templates, and those were not supposed to be draggable in the treeview. However, the code that was trying to prevent the dragging didn't work. These changes fix that.
Tested if virtual templates were prevented from being dragged, and if normal templates can still be dragged.
N/A
[Asana ticket](https://app.asana.com/0/1201027711166952/1207832033914496)
> Disable dragging for virtual templates

- Api/Api.csproj
- Api/Core/Queries/WiserInstallation/CreateDedicatedLinkTableTriggers.sql
- Api/Modules/LinkSettings/Services/LinkSettingsService.cs
When enabling the setting `UseDedicatedTable` on a link type in the admin module, Wiser will now automatically create those tables and triggers for that link type, if they don't exist yet.
By enabling the setting `UseDedicatedTable` on a link type and checking if the tables and triggers are correctly created.
N/A
I couldn't find an Asana ticket for this. I started working on this on the 17th of januari and never finished it until now. Finished it now because we noticed this old branch.
> Create dedicated link tables in admin module

- FrontEnd/Modules/DynamicItems/Scripts/Fields.js
Now when due to dependencies all fields in a group or tab are hidden, the group or tab also gets hidden.
Set up a test item with a checkbox with dependant fields that were hidden when the checkbox is unchecked and tested the solution using this item.
When it worked with this I tested it with an item without groups.
N/A
https://app.asana.com/0/1201027711166952/1207942309001520/f
> Hide groups and tabs when all fields are hidden

- Api/Modules/Templates/Services/TemplatesService.cs
- FrontEnd/Modules/Templates/Scripts/Templates.js
When running the WTS locally it would search for templates on the development environment. But when saving a template it would be set to no environment causing problems. This prevents that while still working correctly when deploying to the other environments.
Tested by creating a new template, modifying/saving it and deploying it to different environments using the save and deploy to test, dropdowns and version control. In all cases the template create a new version at the correct moment and set the corrent environment.
N/A
https://app.asana.com/0/1201027711166952/1207812386630781
> Fix the environment of templates

- FrontEnd/Modules/Admin/Scripts/RoleTab.js
The checkboxes did not have unique IDs causing the labels to always reference the first one they find. These have now be made unique so that the labels can correspond with the unique checkbox.
Tested by changing the permissions of a role on different tabs and types (read, write, etc.) and check if the correct boxes are checked after the permissions have been updated by the API and the information is changed in the database.
N/A
https://app.asana.com/0/1201027711166952/1208124350911987
> Give unique ids to checkboxes to trigger correct one

- Api/Api.csproj
- Api/Modules/Templates/Services/DataLayer/TemplateDataService.cs
- FrontEnd/FrontEnd.csproj
- Wiser.Tests/Wiser.Tests.csproj
A new template would never be shown in the verison control until it has been saved at least once. Now new templates will be shown to reduce confusion.
And GCL updated
Tested by creating a new template and see if it is in the version control. And check when a new version is made this is not yet reflected in version control.
N/A
https://app.asana.com/0/1201027711166952/1208376046799513
> Set a newly created template always on dirty

- FrontEnd/Core/Scripts/main.js
When the selected branch is set the rendering would start. Due to a race condition data could not be found while rendering the front-end. By changing the order and awaiting the async function the race condition is gone. This also resulted in two function calls to be able to be removed so they are only called within the `onSelectedBranchChange` function.
Tested by checking if after the changes the window correctly opened without error.
N/A
N/A
> Fix race condition for the branch merge window

- Api/Modules/Files/Interfaces/IFilesService.cs
- Api/Modules/Files/Models/SelectionOptions.cs
- Api/Modules/Files/Services/FilesService.cs
- Api/Modules/Pdfs/Controllers/PdfsController.cs
- Api/Modules/Pdfs/Interfaces/IPdfsService.cs
- Api/Modules/Pdfs/Models/MergePdfModel.cs
- Api/Modules/Pdfs/Services/PdfsService.cs
- FrontEnd/Modules/DynamicItems/Scripts/Fields.js
Adds an option to the merge PDF functionality to get the newest or oldest files of an item.
Used the mergeFile action on items that already has previous generated PDF linked to get a merge of PDFs generated in a previous action.
N/A
https://app.asana.com/0/1201394730777422/1208848056082229/f
> Add support for getting latest or earliest file when merging pdfs

- Api/Api.csproj
Removes 2 packages that are no longer used.
- Microsoft.AspNetCore.Authentication.JwtBearer is not used because OpenIddict directly handles the authentication and validation of the JWT tokens now.
- Microsoft.IdentityModel.Protocols.OpenIdConnect was added during implementation of OpenIddict but ended up not being used.
Ran Wiser and logged in
N/A
N/A
> Remove some nuget packages that are no longer used

- FrontEnd/Core/Scripts/shared/databases.service.js
When the user was unauthorized to do database migration, for example due to access token and refresh token being expired.
The user would get an alert that data migrations went wrong and then be redirected to the login. This is confusing for the end user so this adds a check for unauthorized so that no alert gets shown in these scenarios.
Added tokens that would be rejected into localStorage and refreshed the page.  
N/A
N/A
> Don't show database migration alert on unauthorized

- Api/Modules/Items/Services/ItemsService.cs
While checking another issue related to item duplication i ran into a problem with duplicating configurators that were at the root (parent id zero), this was added 2 months ago but after investigating i learned that this check is not needed, parents may be zero in this case. the input variable is unsigned so there is also no need to check for negative ids, this check can be removed completely 
ran it on wiserdemo.
N/A
No Asana ticket for this.
> ParentId may be zero

- Api/Core/Services/ClientDatabaseConnection.cs
during testing i ran into compile issues, seems like checking for retry no longer is valid with the int value that returns, these need to be mysql error codes, i added a cast in 3 places for this, This checks for retries so cast should be save, if no valid value is inserted the check will still not have those values to compare to anyway.
tested on wiserdemo
NA
Not for this
> change errorcode checking for re-try to use casted values in mysqlconection

- Api/Startup.cs
Fixes 2 bugs that has to do with the encryption key for openiddict.
The first bug is that the signing key was used for encryption due to the wrong parameter being given to options.AddEncryptionCertificate.
The second is that the encryption is still needed even if AccessTokenEncryption is disabled. Because of this Wiser wouldn't work if the encryption key isn't given in the appsettings. This is supposed to be optional in Wiser. This is fixed by using the Signing Key as encryption key if none was supplied.
Using a separate encryption key is still recommended.
Tested using the same key as both signing and encryption key.
N/A
https://app.asana.com/0/1201027711166952/1208952541276646/f
> Bugfix openiddict encryption key

- FrontEnd/Modules/DynamicItems/Scripts/Fields.js
in a previous bugfix some variable changes were made for the admin settings, however 1 line was accidentlity replaced while it should have been kept. this commit reverses that change, making the admin context work again
locally with wiserdemo
none
no just related to Gilians pride
> solve issue were admin context menu would not open for admins

- FrontEnd/Modules/Base/Scripts/Utils.js
- FrontEnd/Modules/Dashboard/Views/Dashboard/Index.cshtml
- FrontEnd/Modules/DynamicItems/Scripts/Fields.js
After closing the file manager window the content builder window would not be brought back into focus. This PR fixes that by checking if there's a content builder window active and tries to bring it back into focus.
Used a debug build of Wiser and checked if the content builder window would correctly be brought to the front after the file manager window closes (and thus bringing it back into focus).
None.
[Asana ticket](https://app.asana.com/0/1201027711166952/1207811525392664)
> Focus content builder window

- Api/Core/Queries/WiserInstallation/CreateDedicatedItemTablesTriggers.sql
The query doesn't work at the moment because NEW doesn't exist in that context. This fixes it.
Please describe how you tested your changes and how you confirmed this functionality is not a breaking change.
> Fixed bug in `{tablePrefix}DetailDelete`

- Api/Modules/Queries/Services/StyledOutputService.cs
IT's a small change to make sure we also apply replacements on the begin and end texts in styled outputs
tested it on wiser demo
none
none
> ensure that begin and end styled output also make use of replacements

- Api/Core/Services/ClientDatabaseConnection.cs
The ClientDatabaseConnection didn't load the SSH settings from the GCL section of the app settings making it impossible to connect to databases that require it. By adding this one line to the constructor, this now works as exepcted.
By starting Wiser locally using SSH settings for a connection that I know requires it, and confirming that Wiser works as expected.
None.
No ticket (ran into this while I was busy with something else).
> Added support for SSH settings

- Api/Api.csproj
- Api/Modules/Items/Controllers/ItemsController.cs
- Api/Modules/Items/FieldTemplates/sub-entities-grid.js
- Api/Modules/Items/Interfaces/IItemsService.cs
- Api/Modules/Items/Models/AddOrRemoveLinksRequestModel.cs
- Api/Modules/Items/Services/ItemsService.cs
- FrontEnd/Core/Models/BaseViewModel.cs
- FrontEnd/Core/Services/BaseService.cs
- FrontEnd/FrontEnd.csproj
- FrontEnd/Modules/Base/Scripts/Utils.js
- FrontEnd/Modules/DynamicItems/Controllers/DynamicItemsController.cs
- FrontEnd/Modules/DynamicItems/Scripts/DynamicItems.js
- FrontEnd/Modules/DynamicItems/Scripts/Grids.js
- FrontEnd/Modules/DynamicItems/Scripts/Windows.js
- FrontEnd/Modules/DynamicItems/Views/DynamicItems/Index.cshtml
- Wiser.Tests/Wiser.Tests.csproj
If the source and destination items use different table prefixes, then it would not find the correct link settings and not use `parent_item_id`. This happened most often with link type `1`, because that one is used for multiple entities.
By creating new items with a parent id and checking if correct links are created.
https://github.com/happy-geeks/geeks-core-library/pull/851
https://app.asana.com/1/5038780173035/project/1205090868730163/task/1206957555415824
https://app.asana.com/1/5038780173035/project/1205090868730163/task/1207511625868431
> Fixed problem that creating items with a parentId, would not link them correctly in certain situations

- FrontEnd/Modules/DynamicItems/Scripts/Fields.js
Refreshes the correct item based on entity type to prevent an item from `wiser_item` to be loaded when working with an item in a prefix table.
Tested by refreshing an item that is in both `wiser_item` as a prefix table to check if the correct item is loaded again after the refresh.
N/A
https://app.asana.com/1/5038780173035/project/1205090868730163/task/1205958510251445
> Refresh the correct item with the action button

- Api/Modules/Grids/Services/GridsService.cs
- Api/Modules/Items/Services/ItemsService.cs
Allow permissions for items to be applied to specific entities. This fixes the problem that if permissions are set this is applied to entities in wiser_item and any prefix table with the same ID.
For backwards compatibility, if no entity type is provided with the permission it still applies to all items with the same ID.
Tested by adding a permission for an item and validated the correct behavior if no entity type has been provided, if the entity type of the item in `wiser_item` was provided and the entity type of the item in the prefix table.
https://github.com/happy-geeks/geeks-core-library/pull/857
Wiser update is not dependent on the GCL update, but will not apply the new functionality until a new GCL version is matched. …
> Allow permissions for items to be set to specific entity

- Api/Core/Queries/WiserInstallation/CreateTables.sql
the create table sql is missing a column, halting the creation process of new tenants once again.
> add missing column to creation system
