happy-geeks/wiser

FrontEnd/Modules/DynamicItems/Scripts/Windows.js

READY - Added functionality for adding webp as default for adding images to the webpages

---

Api/Modules/Customers/Services/WiserCustomersService.cs
Api/Modules/Templates/Services/TemplatesService.cs
FrontEnd/Core/Scripts/components/customer-management.js
FrontEnd/Core/Scripts/shared/customers.service.js
FrontEnd/Core/Views/Home/Index.cshtml
FrontEnd/package-lock.json

- Fix missing subdomain in validation;
- Remove obsolete text;
- Fix missing inserted database values;
- Remove obsolete columns.

Fix problems in customer setup.

---

Api/Api.csproj
Api/Core/Queries/WiserInstallation/CreateTables.sql
Api/Modules/DataSelectors/Controllers/DataSelectorsController.cs
Api/Modules/DataSelectors/Interfaces/IDataSelectorsService.cs
Api/Modules/DataSelectors/Models/DataSelectorEntityPropertyModel.cs
Api/Modules/DataSelectors/Services/DataSelectorsService.cs
FrontEnd/Modules/DataSelector/Scripts/Connection.js
FrontEnd/Modules/DataSelector/Scripts/DataLoad.js
FrontEnd/Modules/DataSelector/Scripts/DataSelector.js
FrontEnd/Modules/DataSelector/Views/DataSelector/Index.cshtml

Fixes some issues with the data selector and updates the GCL version to 1.0.6.1 which also contains fixes for the data selector.

Data selector changes

---

FrontEnd/package-lock.json
FrontEnd/package.json
FrontEnd/webpack.config.js

Webpack upgrade

---

Api/Api.csproj
FrontEnd/FrontEnd.csproj

This version fixes the ShoppingBasket component's query fields not being
query editors in the front-end.

Updated GCL to version 1.2.5

---

FrontEnd/FrontEnd.csproj
FrontEnd/Modules/Base/Scripts/Utils.js
FrontEnd/Modules/Base/Scripts/codemirror/scss-lint.js
FrontEnd/Modules/Base/Scripts/codemirror/scsslint.js
FrontEnd/Modules/Templates/Css/Templates.css
FrontEnd/Modules/Templates/Scripts/Templates.js
FrontEnd/Modules/Templates/Views/Templates/Partials/CssSettings.cshtml
FrontEnd/Modules/Templates/Views/Templates/Partials/HtmlSettings.cshtml
FrontEnd/Modules/Templates/Views/Templates/Partials/JavascriptSettings.cshtml
FrontEnd/Modules/Templates/Views/Templates/Partials/QuerySettings.cshtml
FrontEnd/Modules/Templates/Views/Templates/Partials/ScssSettings.cshtml

- Search bar was not visible because of missing css file.
- Warnings/errors were not visible because of z-index.
- ES6 was not supported with lint.
- SCSS was nog supported with lint.

Templates - Fixed issues with codemirror

---

FrontEnd/Core/Scss/fonts.scss
FrontEnd/Core/Scss/variables.scss
FrontEnd/Modules/Base/Css/fonts.css
FrontEnd/Modules/Base/Css/kendo.custom.css
FrontEnd/Modules/Base/Css/kendo.wiser.css
FrontEnd/Modules/Base/Css/masterpage.css
FrontEnd/Modules/Base/Css/variables.css

Gridview issues en sticky footer issues opgelost.

Styling issues met gridview velden + open source font added

---

Api/Core/Helpers/IdentityHelpers.cs
Api/Core/Models/IdentityConstants.cs
Api/Core/Queries/WiserInstallation/InsertInitialData.sql
Api/Core/Services/WiserGrantValidator.cs
Api/Modules/Templates/Services/DynamicContentService.cs
Api/Modules/Templates/Services/TemplatesService.cs
FrontEnd/Modules/Templates/Scripts/DynamicContent.js
FrontEnd/Modules/Templates/Scripts/Templates.js
FrontEnd/Modules/Templates/Views/DynamicContent/Partials/InputGenerator.cshtml
FrontEnd/Modules/Templates/Views/Templates/Partials/CssSettings.cshtml
FrontEnd/Modules/Templates/Views/Templates/Partials/HtmlSettings.cshtml
FrontEnd/Modules/Templates/Views/Templates/Partials/JavascriptSettings.cshtml
FrontEnd/Modules/Templates/Views/Templates/Partials/QuerySettings.cshtml
FrontEnd/Modules/Templates/Views/Templates/Partials/ScssSettings.cshtml
FrontEnd/Modules/Templates/Views/Templates/Tabs/HistoryTab.cshtml

Several bug fixes and improvements to the templates module.

Template module imporvements

---

FrontEnd/Modules/DynamicItems/Scripts/Windows.js

- Set correct property name;
- Generate correct URL.

Fix the image upload.

---

FrontEnd/Modules/DynamicItems/Scripts/Windows.js
FrontEnd/Modules/DynamicItems/Views/DynamicItems/Index.cshtml

The insert image popup now contains an input to set an alt text which will be set on the image. Even if the input is empty, the alt attribute will still be added, but with an empty value.
Asana punt: https://app.asana.com/0/1201027711166952/1202116700725965

Added alt text input

---

Api/Modules/Templates/Models/Template/TemplateSettingsModel.cs
Api/Modules/Templates/Services/DataLayer/TemplateDataService.cs
FrontEnd/Modules/Templates/Scripts/Templates.js
FrontEnd/Modules/Templates/Services/FrontEndDynamicContentService.cs
FrontEnd/Modules/Templates/Views/Templates/Partials/HtmlSettings.cshtml

Asana punten:
- https://app.asana.com/0/1201027711166952/1201990704258296
- https://app.asana.com/0/1201027711166952/1202033230311228
- https://app.asana.com/0/1201027711166952/1202017791715427

Template module fixes and changes

---

Api/Modules/DataSelectors/Services/DataSelectorsService.cs

https://app.asana.com/0/1201027711166952/1201422461305695
Together with: https://github.com/happy-geeks/geeks-core-library/pull/116

Allow secure dataselectors to be loaded insecure from a secure location.

---

Api/Modules/Templates/Services/TemplatesService.cs

Added fallback to use the non-minified JavaScript for the MinifiedValue property if the minification failed.
Asana: https://app.asana.com/0/1201027711166952/1202017783221638

Added JavaScript minify fallback

---

Api/Modules/Items/Controllers/ItemsController.cs
Api/Modules/Items/Interfaces/IItemsService.cs
Api/Modules/Items/Services/ItemsService.cs
FrontEnd/Modules/DynamicItems/Scripts/DynamicItems.js
FrontEnd/Modules/DynamicItems/Scripts/Fields.js
FrontEnd/Modules/DynamicItems/Scripts/Grids.js

The getItemDetails function now uses a new method to retrieve item details that also supports the setting of the entity type to support table prefixes.
Asana: https://app.asana.com/0/1201394730777422/1202307747750013 & https://app.asana.com/0/1201394730777422/1202312095946652

Refactored the getItemDetails function

---

Api/Modules/Items/FieldTemplates/action-button.html
Api/Modules/Items/Services/ItemsService.cs

Changed action-button.html and GetItemHtmlAsync in ItemsService to implement accesskey property
Asana: [https://app.asana.com/0/1201027711166952/1202018557374569](https://app.asana.com/0/1201027711166952/1202018557374569)

Implementation accesskey for action-button

---

FrontEnd/Modules/ImportExport/Scripts/RemoveItems.js

#EntityTypesContainer changed in kendoComboBox
Asana: [https://app.asana.com/0/1201027711166952/1201872990075500](https://app.asana.com/0/1201027711166952/1201872990075500)

RemoveItem.js - changed EntityTypesContainer to kendoComboBox

---

Api/Modules/Modules/Models/ModuleAccessRightsModel.cs
Api/Modules/Modules/Services/ModulesService.cs
FrontEnd/Modules/ImportExport/Scripts/Export.js

https://app.asana.com/0/1201027711166952/1201144624513230

Only show modules in the export that can actually be exported.

---

Api/Api.csproj
Api/Modules/Templates/Controllers/TemplatesController.cs
Api/Modules/Templates/Helpers/ReflectionHelper.cs
Api/Modules/Templates/Interfaces/ITemplatesService.cs
Api/Modules/Templates/Models/Template/TemplateSettingsModel.cs
Api/Modules/Templates/Services/CachedTemplatesService.cs
Api/Modules/Templates/Services/DataLayer/HistoryDataService.cs
Api/Modules/Templates/Services/DataLayer/TemplateDataService.cs
Api/Modules/Templates/Services/HistoryService.cs
Api/Modules/Templates/Services/TemplatesService.cs
FrontEnd/FrontEnd.csproj
FrontEnd/Modules/Templates/Css/Templates.css
FrontEnd/Modules/Templates/Scripts/Templates.js
FrontEnd/Modules/Templates/Views/Templates/Partials/HtmlSettings.cshtml

HTML templates now have additional 
Asana: https://app.asana.com/0/1201027711166952/1202011980071142

Add default header and footer options for templates

---

FrontEnd/Core/Scripts/main.js
FrontEnd/Core/Scss/masterpage.scss
FrontEnd/Core/Views/Home/Index.cshtml
FrontEnd/Modules/Base/Css/kendo.wiser.css
FrontEnd/Modules/Base/Css/masterpage.css

In enkele modules was scrollen niet mogelijk. Dit is verholpen.

Scrolling issues in several modules resolved

---

Api/Core/Queries/WiserInstallation/CreateTables.sql
Api/Modules/Modules/Services/ModulesService.cs

wiser_entity has been added to the WiserTableDefinitions in the GCL that has the new column included.

Add delete_action column to wiser_entity.

---

FrontEnd/Modules/DynamicItems/Css/DynamicItems.css

Virtual scrolling vervangen door native scroll styling

Virtual scroll replaced by native scroll.

---

FrontEnd/Core/Scss/icons.scss
FrontEnd/Modules/Admin/Scripts/ModuleTab.js
FrontEnd/Modules/Base/Css/icons.css
FrontEnd/Modules/Base/Css/kendo.custom.css
FrontEnd/Modules/Base/Css/kendo.wiser.css

Small styling issues + icon dropdown enhanced so the actual icon is shown
The last issue needs further programming

Small styling issues + icon dropdown enhanced so the actual icon is shown

---

FrontEnd/Modules/Admin/Css/Admin.css
FrontEnd/Modules/Base/Css/kendo.custom.css
FrontEnd/Modules/Base/Css/kendo.wiser.css
FrontEnd/Modules/Base/Css/masterpage.css
FrontEnd/Modules/Base/Css/variables.css
FrontEnd/Modules/DynamicItems/Css/DynamicItems.css

Styling issues opgelost betreffende:
- KendoNotification: postion + background-colors
- Admin-module: input field width + paddings and margins
- Sticky footer: meta data + unwanted scrollbar

Styling issues - KendoNotification, Admin-module, sticky footer

---

Api/Core/Queries/WiserInstallation/CreateTables.sql
Api/Modules/Grids/Services/GridsService.cs
Api/Modules/Items/FieldTemplates/HTMLeditor.js
FrontEnd/Modules/DynamicItems/Scripts/DynamicItems.js

* Fixed bug that the table "wiser_itemfile_archive" was missing the column "protected" for new customers.
* Added functionality to DynamicItems module for loading a pre-specified item when no item is selected in the tree view.
* Added extra mode to HTML editors with only the most basic tools and content builder and html source tools.

Features and bug fixes

---

Api/Core/Services/WiserGrantValidator.cs
Api/Modules/Customers/Controllers/UsersController.cs
Api/Modules/Customers/Models/UserModel.cs
Api/Modules/Customers/Services/UsersService.cs
FrontEnd/Core/Scripts/components/login.js

When a user logs in and is required to change the password the old password cannot be used for the new password.
https://app.asana.com/0/1201027711166952/1202463295129611

Validate if the old and new passwords are different

---

FrontEnd/Modules/Templates/Css/DynamicContent.css
FrontEnd/Modules/Templates/Css/Preview.css
FrontEnd/Modules/Templates/Css/Templates.css
FrontEnd/Modules/Templates/Scripts/DynamicContent.js
FrontEnd/Modules/Templates/Views/DynamicContent/Index.cshtml
FrontEnd/Modules/Templates/Views/Templates/Tabs/PreviewTab.cshtml

Dynamic Content styling issues opgelost + smart sticky header toegevoegd

Styling issues Dynamic Content etc.

---

FrontEnd/Modules/Admin/Css/Admin.css
FrontEnd/Modules/Base/Css/kendo.custom.css
FrontEnd/Modules/DataSelector/Css/DataSelector.css

Verschillende onderdelen hadden enkele styling issues + bij de treeview waren er enkele styling wensen.

Latest styling issues resolved

---

FrontEnd/Modules/Templates/Css/Templates.css

Reduced the font size slightly and added a line clamp for 3 lines with an ellipsis as overflow.
[Asana task](https://app.asana.com/0/1201027711166952/1202808042425187/f)

Added line clamp to dialog title

---

FrontEnd/Modules/Base/Css/kendo.wiser.css

Background van de uploader preview aangepast (css only)

Uploader - blocked background in uploader preview using CSS only

---

FrontEnd/Modules/Base/Css/kendo.wiser.css
FrontEnd/Modules/Base/Css/masterpage.css
FrontEnd/Modules/Templates/Css/DynamicContent.css
FrontEnd/Modules/Templates/Css/Preview.css

Styling issues die veelal het gevolg zijn van de laatste Kendo UI update verholpen.

Corrected styling issues as a result of latest Kendo UI update

---

FrontEnd/Modules/Templates/Scripts/Templates.js

Added the save template action to the save button in the html editor.
This will save the html as well as the template when pressing the save button in the html editor.
The same feature can be triggered through the Ctrl-S keyboard action.
[Asana task](https://app.asana.com/0/1201027711166952/1202666985299717/f)

Added save template action to save button.

---

Api/Modules/Files/Services/FilesService.cs

https://app.asana.com/0/1200923549887805/1202906679310142

Fix the deletion of a file when it has no file path.

---

FrontEnd/Modules/Base/Css/kendo.custom.css
FrontEnd/Modules/Base/Css/kendo.wiser.css
FrontEnd/Modules/Base/Css/masterpage.css
FrontEnd/Modules/Templates/Css/DynamicContent.css
FrontEnd/Modules/Templates/Css/Templates.css
FrontEnd/Modules/Templates/Scripts/Templates.js
FrontEnd/Modules/Templates/Views/Templates/Index.cshtml
FrontEnd/Modules/Templates/Views/Templates/Partials/PublishedEnvironments.cshtml

- Layout van de templatemodule is aangepast
- Enkele kleine styling issues opgelost
- Ontbrekende iconen hersteld

Styling issues + adjustments to the templatemodule layout

---

FrontEnd/Core/Scss/masterpage.scss
FrontEnd/Modules/Admin/Scripts/ModuleTab.js
FrontEnd/Modules/Base/Css/kendo.wiser.css
FrontEnd/Modules/Base/Css/masterpage.css

Een aantal kleine styling issues opgelost
- Inline checkboxes onder elkaar
- Iconen dropdown hoger gemaakt
- Logo in switch knop beter uitgelijnd
- Styling kleine popup gecontroleerd

Styling issues + additional wishes resolved

---

FrontEnd/Modules/DataSelector/Controllers/DataSelectorController.cs
FrontEnd/Modules/DataSelector/Scripts/Connection.js
FrontEnd/Modules/DataSelector/Scripts/DataSelector.js

* Fixed some issues that were caused by the Kendo UI update.
* Fixed issue that the "export mode" couldn't be enabled anymore.
https://app.asana.com/0/1201027711166952/1203030573608285

Fixed DataSelector issues

---

FrontEnd/Modules/Base/Css/masterpage.css
FrontEnd/Modules/Communication/Css/Index.css
FrontEnd/Modules/Communication/Scripts/Index.js
FrontEnd/Modules/Communication/Views/Communication/Index.cshtml

Communicationmodule icons replaced + styling adjusted

Communicationmodule icons replaced + styling adjusted

---

FrontEnd/Modules/DynamicItems/Scripts/Fields.js

De 3de replace moet windowLinkType bevatten ipv windowLinkId zodat dit weer correct werkt en een bug oplost.
Asana link:
https://app.asana.com/0/1201027711166952/1203244639580878

Changed third windowLink to type so it works correctly

---

FrontEnd/Modules/DynamicItems/Scripts/Fields.js

Extra parameters toegevoegd zodat files correct opgehaald kunnen worden bij het opslaan van files.
Asana link:
https://app.asana.com/0/1201027711166952/1203252348295284

Added extra parameters to URL to fix the image upload

---

FrontEnd/Core/Scss/kendo-custom.scss
FrontEnd/Core/Scss/task-alerts.scss
FrontEnd/Modules/Base/Css/kendo.wiser.css

Styling issues uit diverse Asana-items hersteld.

Styling issues resolved

---

FrontEnd/Core/Scripts/main.js
FrontEnd/Core/Scss/branches.scss
FrontEnd/Core/Scss/dialog.scss
FrontEnd/Core/Views/Home/Index.cshtml

https://app.asana.com/0/1201027711166952/1203310497905681

Some improvements for branches functionality

---

FrontEnd/Modules/DynamicItems/Scripts/Windows.js

https://app.asana.com/0/1201027711166952/1202964871872783

Add images with the extension it has been uploaded with.

---

Api/Modules/DataSelectors/Controllers/DataSelectorsController.cs
Api/Modules/DataSelectors/Interfaces/IDataSelectorsService.cs
Api/Modules/DataSelectors/Models/DataSelectorModel.cs
Api/Modules/DataSelectors/Services/DataSelectorsService.cs
Api/Modules/Templates/Services/TemplatesService.cs
FrontEnd/Modules/DataSelector/Scripts/DataLoad.js
FrontEnd/Modules/DataSelector/Scripts/DataSelector.js
FrontEnd/Modules/DataSelector/Views/DataSelector/Index.cshtml

Get results from data selectors as JSON with option to combine it to a key-value paired object.
Depends on: https://github.com/happy-geeks/geeks-core-library/pull/221
https://app.asana.com/0/1201027711166952/1203114958448432

Add endpoint to Wiser API to execute data selectors.

---

Api/Core/Queries/WiserInstallation/InsertInitialData.sql
Api/Modules/Items/FieldTemplates/HTMLeditor.js
Api/Modules/Items/Services/ItemsService.cs
FrontEnd/Modules/DynamicItems/Scripts/Fields.js
FrontEnd/package-lock.json
FrontEnd/package.json

* Added setting to decide whether to use ContentBox or ContentBuilder for each tenant.
* Downgraded to a lower version of ContentBox and ContentBuilder, because more recent versions have a bug that causes it to change the wrong classes when you use col-md and col-sm classes at the same time.

Content box fixes

---

FrontEnd/Modules/Admin/Scripts/EntityTab.js

Fixed a bug where getting the tab called "Gegevens" didn't work.
Asana link:
https://app.asana.com/0/1201027711166952/1203199919032334

Getting the Gegevens tab works again

---

Api/Core/Queries/WiserInstallation/CreateTables.sql
Api/Modules/Files/Controllers/FilesController.cs
Api/Modules/Files/Interfaces/IFilesService.cs
Api/Modules/Files/Models/FileExtraDataModel.cs
Api/Modules/Files/Models/FileModel.cs
Api/Modules/Files/Services/FilesService.cs
Api/Modules/Items/Services/ItemsService.cs
FrontEnd/Modules/DynamicItems/Scripts/Fields.js
FrontEnd/Modules/DynamicItems/Views/DynamicItems/Index.cshtml

This is made so that we can use different alt texts per language per image on a website. But it can also be used for other things in the future.
Asana ticket: https://app.asana.com/0/1201027711166952/1202813905771955
Corresponding GCL PR: https://github.com/happy-geeks/geeks-core-library/pull/222

Item files can now have extra data

---

FrontEnd/Core/Scss/branches.scss
FrontEnd/Core/Views/Home/Index.cshtml

https://app.asana.com/0/5038781037393/1203548008587458

Branches dialog adjustments

---

FrontEnd/Modules/Base/Css/kendo.custom.css
FrontEnd/Modules/Templates/Css/Templates.css
FrontEnd/Modules/Templates/Views/Templates/Partials/LinkedTemplates.cshtml

https://app.asana.com/0/5038781037393/1203431725050824

Position issues templates-module resolved

---

FrontEnd/Modules/Admin/Scripts/EntityTab.js

https://app.asana.com/0/5038781037393/1202988286054823

Kendo dialog settings changed/added

---

Api/Core/Queries/WiserInstallation/InsertInitialData.sql
FrontEnd/Modules/Templates/Views/Templates/Partials/HtmlSettings.cshtml

Asana: https://app.asana.com/0/1201027711166952/1201977750164602
This also needs a PR from the GCL: https://github.com/happy-geeks/geeks-core-library/pull/255

Added functionality for caching templates and components based on an URL regex.

---

Api/Modules/Grids/Services/GridsService.cs

Adding a check for reserved Javascript values and throwing an exception if `fieldName` matches a reserved value.
Asana link: https://app.asana.com/0/1201027711166952/1203330222343490

Added check on reserved values in Javascript

---

Api/Modules/Customers/Controllers/UsersController.cs
Api/Modules/Customers/Interfaces/IUsersService.cs
Api/Modules/Customers/Services/CachedUsersService.cs
Api/Modules/Customers/Services/UsersService.cs
FrontEnd/Core/Scripts/store/index.js

Added generic methods for saving and loading user settings. The grids and dashboard saving and loading methods now use these new methods.
Related Asana task: https://app.asana.com/0/1182779092805226/1201031439734820

Saving and loading user settings

---

FrontEnd/Modules/VersionControl/Scripts/VersionControl.js

You can now Resize the collums. 
https://app.asana.com/0/1201027711166952/1203601461297521

Versioncontrol colum is resizeble

---

Api/Modules/Grids/Services/GridsService.cs
Api/Modules/Templates/Services/TemplatesService.cs

Also added IgnoreCase and Compiled flags to most of them to make them run faster.
No Asana ticket for this.

Added timeouts to all regexes so that they can no longer be abused for DDOS attacks.

---

Api/Modules/ApiConnections/Controllers/ApiConnectionsController.cs
Api/Modules/ApiConnections/Interfaces/IApiConnectionsService.cs
Api/Modules/ApiConnections/Models/ApiConnectionModel.cs
Api/Modules/ApiConnections/Services/ApiConnectionsService.cs
Api/Modules/EntityTypes/Controllers/EntityTypesController.cs
Api/Modules/EntityTypes/Interfaces/IEntityTypesService.cs
Api/Modules/EntityTypes/Services/EntityTypesService.cs
Api/Modules/Templates/Services/TemplatesService.cs
Api/appsettings.json
FrontEnd/Core/Controllers/ExternalApisController.cs
FrontEnd/Core/Interfaces/IExternalApisService.cs
FrontEnd/Core/Services/BaseService.cs
FrontEnd/Core/Services/ExternalApisService.cs
FrontEnd/Modules/Base/Scripts/Utils.js
FrontEnd/Modules/DynamicItems/Scripts/DynamicItems.js
FrontEnd/Modules/DynamicItems/Scripts/Fields.js
FrontEnd/Startup.cs

This functionality existed in Wiser 2, I finally implemented it in Wiser 3 as well now. There is no Asana ticket for this.

Implemented functionality for calling external APIs when updating items in Wiser

---

Api/Modules/Grids/Services/GridsService.cs
FrontEnd/Modules/Admin/Scripts/InfoText.js
FrontEnd/Modules/Admin/Scripts/ModuleTab.js
FrontEnd/Modules/Admin/Views/Admin/Index.cshtml
FrontEnd/Modules/Base/Css/kendo.wiser.css
FrontEnd/Modules/Base/Scripts/Utils.js
FrontEnd/Modules/TaskAlerts/Css/TaskAlerts.css
FrontEnd/Modules/TaskAlerts/Css/TaskHistory.css
FrontEnd/Modules/TaskAlerts/Scripts/TaskAlerts.js
FrontEnd/Modules/TaskAlerts/Scripts/TaskHistory.js
FrontEnd/Modules/TaskAlerts/Scripts/TaskUtils.js
FrontEnd/Modules/TaskAlerts/Views/TaskAlerts/History.cshtml
FrontEnd/Modules/TaskAlerts/Views/TaskAlerts/Index.cshtml

* Fixed problem that task history didn't load anymore.
* Fixed some styling issues with filtering.
* Added default sorting to due date descending.
* Added functionality to return completed tasks back to todo list.
Asana ticket: https://app.asana.com/0/1201027711166952/1147498761589385

Improvements for tasks

---

Api/Modules/Items/FieldTemplates/item-linker.js
Api/Modules/Items/FieldTemplates/sub-entities-grid.js
FrontEnd/Modules/Base/Css/kendo.wiser.css
FrontEnd/Modules/DynamicItems/Scripts/Grids.js

Asana ticket: https://app.asana.com/0/1201027711166952/1203651395256949

Added new option to all grids for opening items in a new tab.

---

Api/Modules/Grids/Services/GridsService.cs

The filters that were provided did not yet get used in the queries.
https://app.asana.com/0/1201027711166952/1203797471558661

Add filters to the history grid.

---

FrontEnd/Modules/DataSelector/Scripts/Connection.js
FrontEnd/Modules/DataSelector/Scripts/DataSelector.js

The data selector module stopped working after an update to webpack. These changes to the scripts fix the issues.
Asana: https://app.asana.com/0/1201027711166952/1203890936701612

Fixed data selector module not working anymore

---

Api/Modules/Branches/Services/BranchesService.cs

Added replacement for an illegal character (') while making branches.
Asana link: https://app.asana.com/0/1201027711166952/1203780838744376

Added extra illegal character for making branches

---

.github/workflows/publish-new-release-ext-1-live.yml
.github/workflows/publish-new-release-ext-1-test.yml

Added workflows for an external installation of Wiser
Asana link:
https://app.asana.com/0/1144661858028300/1204116957445277

Added workflows for an external installation of Wiser

---

Api/Modules/Customers/Models/UserModel.cs
Api/Modules/Customers/Services/UsersService.cs
Api/Modules/Files/Controllers/FilesController.cs
Api/Modules/Files/Interfaces/IFilesService.cs
Api/Modules/Files/Interfaces/Repository/IFilesRepository.cs
Api/Modules/Files/Models/Constants.cs
Api/Modules/Files/Models/FileTreeViewModel.cs
Api/Modules/Files/Services/FilesService.cs
Api/Modules/Files/Services/Repository/FilesRepository.cs
Api/Modules/Templates/Services/TemplatesService.cs
FrontEnd/Modules/Base/Css/masterpage.css
FrontEnd/Modules/Base/Scripts/Utils.js
FrontEnd/Modules/FileManager/Css/FileManager.css
FrontEnd/Modules/FileManager/Scripts/FileManager.js
FrontEnd/Modules/FileManager/Views/FileManager/Index.cshtml

* Added link to copy the URL of an image or other file to clipboard.
* Added tabstrip so that you can easily switch between the different file managers.
* Refactored the back-end code to properly use controllers and services. 
Asana ticket: https://app.asana.com/0/1201027711166952/1204336876526213

Several improvements to the FileManager module

---

FrontEnd/Modules/VersionControl/Css/VersionControl.css
FrontEnd/Modules/VersionControl/Scripts/VersionControl.js

Clickable grid-cells

---

FrontEnd/Modules/Admin/Css/Admin.css

https://app.asana.com/0/1204238738991859/1203674456435689/f

Remove arrow from left pane in wiser admin module

---

Api/Modules/Templates/Services/TemplatesService.cs
FrontEnd/Modules/Admin/Scripts/RoleTab.js

https://app.asana.com/0/0/1203927101085464/f

Change default permissions in admin module to having no permsissions

---

FrontEnd/Modules/Admin/Scripts/EntityTab.js

Datasource will now be saved when using list of entities as datasource
https://app.asana.com/0/0/1204409280999954/f
https://app.asana.com/0/0/1203721009899523/f

Fix bug in multiselect fields in entity admin module

---

FrontEnd/Modules/Admin/Scripts/WiserLinkTab.js
FrontEnd/Modules/Admin/Views/Admin/Index.cshtml

https://app.asana.com/0/0/1204088767479156/f

Add deletion functionality to wiser-item admin tab

---

FrontEnd/Modules/ImportExport/Views/ImportExport/Export.cshtml
FrontEnd/Modules/ImportExport/Views/ImportExport/Import.cshtml

The wrong JavaScript files were loaded causing the modules to start incorrectly. Setting the correct scripts solves this.
https://app.asana.com/0/1201027711166952/1204468301963018

Set correct JavaScript files to load to fix modules.

---

Api/Modules/Items/Controllers/ItemsController.cs
Api/Modules/Items/Interfaces/IItemsService.cs
Api/Modules/Items/Services/ItemsService.cs
Api/Modules/Templates/Services/TemplatesService.cs
FrontEnd/Modules/DynamicItems/Scripts/DynamicItems.js

Fixed problem that published environment was set to 4 instead of 15 when publishing items to production via Wiser tree view.
Also refactored code so that it uses controller and services, instead of a custom query in TemplatesService.
Asana ticket: https://app.asana.com/0/1201027711166952/1204220188325616

Improvements to publishing items in Wiser

---

Api/Modules/Imports/Services/ImportsService.cs

https://app.asana.com/0/1201027711166952/1204521038245457/f

Skip entity type check if no items are being imported

---

Api/Modules/DataSelectors/Controllers/DataSelectorsController.cs
Api/Modules/DataSelectors/Interfaces/IDataSelectorsService.cs
Api/Modules/DataSelectors/Services/DataSelectorsService.cs
Api/Modules/EntityTypes/Controllers/EntityTypesController.cs
Api/Modules/EntityTypes/Interfaces/IEntityTypesService.cs
Api/Modules/EntityTypes/Services/EntityTypesService.cs
Api/Modules/Items/FieldTemplates/radiobutton.js
Api/Modules/Templates/Services/TemplatesService.cs
FrontEnd/Modules/Admin/Scripts/EntityTab.js
FrontEnd/Modules/DataSelector/Scripts/DataLoad.js
FrontEnd/Modules/DataSelector/Scripts/DataSelector.js
FrontEnd/Modules/DataSelector/Views/DataSelector/Index.cshtml

This is still an ongoing project, there are still 47 queries that need to be refactored. But we don't have to do all at once, that's why I already made a pull request.
Please don't remove this branch if you approve this PR, so that I can continue in this branch later and make a new PR.
Asana ticket: https://app.asana.com/0/1201027711166952/1202667476734485

Refactored some old queries to properly use MVC and removed lots of unused queries

---

FrontEnd/Modules/Admin/Scripts/EntityTab.js

https://app.asana.com/0/0/1203674826441306/f
Fixes error in wiser admin that occurs when saving an entity property after the order in the listview gets changed and improves error handling during saving of property

Entity property position change error fix

---

FrontEnd/Modules/VersionControl/Css/VersionControl.css

Sticky footer fix

---

Api/Modules/Branches/Controllers/BranchesController.cs
Api/Modules/Branches/Interfaces/IBranchesService.cs
Api/Modules/Branches/Services/BranchesService.cs
FrontEnd/Core/Scripts/main.js
FrontEnd/Core/Scripts/shared/branches.service.js
FrontEnd/Core/Scripts/store/index.js
FrontEnd/Core/Scripts/store/mutation-types.js
FrontEnd/Core/Views/Home/Index.cshtml

Corresponding WTS PR: https://github.com/happy-geeks/wiser-task-scheduler/pull/96
Asana ticket: https://app.asana.com/0/1201027711166952/1204924239600564
---
- https://app.asana.com/0/0/1204547188872883

Added functionality for deleting Wiser branches.

---

Api/Core/Queries/WiserInstallation/CreateTables.sql
Api/Modules/Queries/Controllers/StyledOutputController.cs
Api/Modules/Queries/Interfaces/IStyledOutputService.cs
Api/Modules/Queries/Models/StyledOutputModel.cs
Api/Modules/Queries/Services/QueriesService.cs
Api/Modules/Queries/Services/StyledOutputService.cs

Asana: https://app.asana.com/0/1200923549887805/1204976361057387/f
the first version of the new styledoutput api, will expect this to be further improved as its rather crude right now but for now this should allow more control over the output of our queries.

add styled output api endpoint

---

Api/Api.csproj
FrontEnd/FrontEnd.csproj

version bump, could not push directly on dev since its protected

increase GCL version to 3.0.22

---

Api/Modules/Files/Services/FilesService.cs
Api/Modules/Items/FieldTemplates/file-upload.js
FrontEnd/Modules/Base/Scripts/Utils.js
FrontEnd/Modules/DynamicItems/Scripts/Fields.js

* Fixed error that always occurred when adding an URL to a file, instead of uploading one manually.
* Fixed problem that after uploading a new file, the date was in English instead of Dutch.
* Fixed problem that adding an URL would show an invalid date and the link to the file wouldn't work, until refreshing the item.
Asana ticket: https://app.asana.com/0/1201027711166952/1204905079533010/f

Fixed several problems with file-upload fields

---

Api/Modules/Queries/Controllers/StyledOutputController.cs
Api/Modules/Queries/Interfaces/IStyledOutputService.cs
Api/Modules/Queries/Services/StyledOutputService.cs

add pagination support for styled out

add pagination support for styled out

---

Api/Modules/Queries/Interfaces/IStyledOutputService.cs
Api/Modules/Queries/Services/StyledOutputService.cs

asana: https://app.asana.com/0/1201027711166952/1205169244716095/f
Add cyclic loop detection to styled output

add detection for cyclic loops inside styled output feature

---

Api/Modules/Queries/Controllers/StyledOutputController.cs
Api/Modules/Queries/Interfaces/IStyledOutputService.cs
Api/Modules/Queries/Services/StyledOutputService.cs

add optional resultsPerPage parameter to styledOutputService
Asana: none, just good to have

add optional resultsPerPage parameter to styledOutputService

---

Api/Api.csproj
FrontEnd/FrontEnd.csproj
FrontEnd/Modules/Dashboard/Views/Dashboard/Index.cshtml
Wiser.Tests/Wiser.Tests.csproj

created version 3.4.10

---

Api/Modules/Queries/Services/StyledOutputService.cs

Asana: https://app.asana.com/0/1201027711166952/1205324515893565/f
improve StyledOutputService by using stringbuilder class instead of default string additions

improve StyledOutputService by using stringbuilder class instead of default string additions

---

Api/Modules/Cache/Services/ExternalCacheService.cs

https://app.asana.com/0/1201027711166952/1204505735096353/f

Add support for JCL cache clear

---

Api/Modules/Items/FieldTemplates/multiselect.html
Api/Modules/Items/FieldTemplates/multiselect.js

https://app.asana.com/0/1201027711166952/1204905085505989/f
Add option for new item button to multi select like already exists on the combobox.

Add new item button to multiselect

---

FrontEnd/Modules/Admin/Scripts/WiserLinkTab.js

https://app.asana.com/0/0/1204853567388907/f
Update wiser link dropdown in the admin screen after save making it reflect the new values

Update wiser link dropdown after save

---

FrontEnd/Modules/Admin/Scripts/EntityTab.js

The javascript crashes on the const value used in the for loop.
---
- https://app.asana.com/0/0/1205556425496897

Saving a ComboBox entity using static values doesn't work

---

FrontEnd/Modules/Admin/Scripts/EntityTab.js
FrontEnd/Modules/Admin/Scripts/WiserQueryTab.js
FrontEnd/Modules/Admin/Views/Admin/Index.cshtml

Replaced action button query id input field with dropdown box to select query. Id of selected query is shown in a label.
---
- https://app.asana.com/0/0/1205448311669684

Replaced id input with dropdown box select

---

FrontEnd/Modules/Admin/Scripts/WiserQueryTab.js
FrontEnd/Modules/Admin/Views/Admin/Index.cshtml
FrontEnd/Modules/Base/Css/masterpage.css

Added a label that shows the selected query id in the admin -> query tab

Exposed query id

---

Api/Modules/Queries/Interfaces/IStyledOutputService.cs
Api/Modules/Queries/Services/StyledOutputService.cs

just kidding, Fix typo in comments

complex large bug fix across 40 files and multiple functions

---

Api/Core/Queries/WiserInstallation/CreateTriggers.sql

https://app.asana.com/0/29553867016121/1205590045783437/f

Add wiser_history triggers for show_in_communication_module

---

Api/Core/Queries/WiserInstallation/CreateTriggers.sql

https://app.asana.com/0/29553867016121/1205590045783437/f

Add wiser_history triggers for store type

---

FrontEnd/Modules/Admin/Scripts/EntityTab.js

https://app.asana.com/0/0/1202988286054817/f
old:
new:

Add explanation to popup for field language copy

---

Api/Modules/Items/Services/ItemsService.cs

Asana ticket: https://app.asana.com/0/1205090868730163/1205521882311963

ItemsService - You can now also save details in the create method, so you no longer have to call the update method to save details for an item.

---

Api/Core/Queries/WiserInstallation/CreateDedicatedItemTablesTriggers.sql

Added the columns `protected` and `extra_data` to the triggers that track history.
[Asana ticket](https://app.asana.com/0/29553867016121/1205590045783437)

Added missing columns in triggers for wiser_itemfile

---

FrontEnd/Modules/Base/Css/masterpage.css
FrontEnd/package-lock.json
FrontEnd/package.json

https://app.asana.com/0/5038781037393/1205465120134073

Error message styling

---

FrontEnd/Core/Scripts/main.js
FrontEnd/Modules/DataSelector/Scripts/DataSelector.js
FrontEnd/Modules/Templates/Scripts/Templates.js

needed for running on Linux where paths are infact captial aware

fix some paths to use the proper capitalization

---

Api/Modules/Tenants/Services/WiserTenantsService.cs

It was a NullReferenceException that only occurred when creating a branch from the main tenant.
Asana ticket: https://app.asana.com/0/1205090868730163/1205666113042067

Fixed bug in WiserTenantsService related to branch creation

---

FrontEnd/Modules/Admin/Css/Admin.css
FrontEnd/Modules/DynamicItems/Css/DynamicItems.css
FrontEnd/Modules/DynamicItems/Scripts/DynamicItems.js
FrontEnd/Modules/DynamicItems/Scripts/Fields.js

Asana ticket: https://app.asana.com/0/1205090868730163/1205556429906716

Fields that are hidden because of dependencies will no longer be checked during form validation

---

Api/Modules/Items/FieldTemplates/combobox.js
Api/Modules/Items/FieldTemplates/multiselect.js
Api/Modules/Items/Services/ItemsService.cs
Api/Modules/Templates/Services/TemplatesService.cs

*  Multiselects still used old functionality for getting data, that did not take current values of other fields into account. Because of this, multiselects didn't get updated properly if they depend on other fields.
* When a field depends on a multiselect field, the value of the multiselect was not added correctly to the query, so the query would always return 0 results.
Asana ticket: https://app.asana.com/0/1205090868730163/1205556425496911

Fixed problems with field dependencies for multiselects

---

Api/Modules/Items/Controllers/ItemsController.cs
Api/Modules/Items/FieldTemplates/combobox.js
Api/Modules/Items/FieldTemplates/multiselect.js
Api/Modules/Items/Interfaces/IItemsService.cs
Api/Modules/Items/Models/SearchRequestModel.cs
Api/Modules/Items/Models/SearchResponseModel.cs
Api/Modules/Items/Services/ItemsService.cs
Api/Modules/Templates/Services/TemplatesService.cs
FrontEnd/Modules/DynamicItems/Scripts/Fields.js

Asana ticket: https://app.asana.com/0/1205090868730163/1205556429906722

Refactored dropdowns and multiselects to fix an issue with searching and to make better readable code

---

Api/Modules/Branches/Services/BranchesService.cs

Asana ticket: https://app.asana.com/0/1201027711166952/1205016361122991

Improved performance of loading all changes of a branch

---

FrontEnd/JS compiler.ps1
FrontEnd/Modules/Admin/Scripts/EntityTab.js
FrontEnd/Modules/Dashboard/Scripts/Dashboard.js
FrontEnd/Modules/Templates/Scripts/Templates.js

There was a bug in the code made for https://app.asana.com/0/1201027711166952/1204420385110393
The kendoTooltip function in Templates.js was not available because the kendoTooltip.js was not imported
Also reduced the amount of jQuery to reduce DOM searches

Bugfix gridtooltips

---

Api/Modules/Dashboard/Services/DashboardService.cs

https://app.asana.com/0/1205090868730163/1205999787016748

Fix error if service has not yet run.

---

FrontEnd/Modules/Base/Css/kendo.custom.css
FrontEnd/Modules/Base/Css/kendo.wiser.css
FrontEnd/Modules/Base/Css/variables.css

- minimal window size for popups (50% of screen) - so small popups don't break the title
- better UI for rows in table (more padding and no lines)
- (more) and variable radius of corners for buttons and windows
This styling was tested on various modules and grids and windows and showed improvement everywhere.

Styling improvements

---

Api/Core/Queries/WiserInstallation/CreateTriggers.sql
Api/Modules/Modules/Services/ModulesService.cs

asana: https://app.asana.com/0/29553867016121/1205590045783437/f

add triggers for styled output table

---

FrontEnd/Modules/Base/Scripts/Utils.js
FrontEnd/Modules/Templates/Controllers/DynamicContentController.cs
FrontEnd/Modules/Templates/Models/DynamicContentViewModel.cs
FrontEnd/Modules/Templates/Scripts/DynamicContent.js
FrontEnd/Modules/Templates/Scripts/Templates.js
FrontEnd/Modules/Templates/Views/DynamicContent/Index.cshtml
FrontEnd/Modules/VersionControl/Scripts/VersionControl.js
FrontEnd/Modules/VersionControl/Views/VersionControl/Index.cshtml

Added button to version control grids to open template history in popup window
Moved history diff generation to Utils, to make accessibility not dependent on Templates class
Added initialTab parameter to DynamicControl route
https://app.asana.com/0/1201027711166952/1205766552804802

Added history popup window to version control template grid

---

Api/Modules/Queries/Services/StyledOutputService.cs

solve a issue where the errors that were generated by sub-styles were ignored and caused parsing errors which gave confusing feedback to the user
asana: https://app.asana.com/0/1200923549887805/1206183838272350/f

solve issue errors for StyledOutput

---

Api/Modules/Queries/Services/StyledOutputService.cs

from remark: https://github.com/happy-geeks/wiser/pull/444#issuecomment-1864432519

add "Async" to HandleInlineStyleElements function

---

Api/Modules/Branches/Controllers/BranchesController.cs
Api/Modules/Branches/Interfaces/IBranchesService.cs
Api/Modules/Branches/Services/BranchesService.cs
FrontEnd/Core/Scripts/main.js
FrontEnd/Core/Scripts/shared/branches.service.js
FrontEnd/Core/Scripts/store/index.js
FrontEnd/Core/Scripts/store/mutation-types.js
FrontEnd/Core/Views/Home/Index.cshtml

* Fixed bug that caused caching of file changes to not work, which was very bad for the performance.
* Added functionality to keep track of and skip any objects that have been both created and deleted again in the branch, because we don't need to merge those, there's also no point in counting them.
* Fixed some compilation errors caused by the new MySQL connector in the GCL.
* Made it so that you can just select from all entities which ones you want to merge, without having to wait for the counting of changes in the branch. Also added an option to skip the check for merge conflicts, so that you can quickly setup a merge without having to wait a long time.
* Fixed some issues in the user interface, that checkboxes weren't always visible.
Asana ticket: …

Several improvements to branches

---

FrontEnd/Modules/Base/Scripts/Utils.js
FrontEnd/Modules/DynamicItems/Scripts/Fields.js

Asana ticket: https://app.asana.com/0/1182779092805226/1204636198695342

Fixed error that occurred when downloading/emailing PDF files, if the filename only contains a number.

---

Api/Modules/Imports/Services/ImportsService.cs

Fixed problem that the import module would always assume that when importing item links, that the destination and the source item would exist in the same table, which is not always the case.
Asana ticket: https://app.asana.com/0/1151477971646641/1206262535753910

Fixed issue in import module with importing links and dedicated tables

---

Api/Modules/Items/FieldTemplates/HTMLeditor.js

Also add a tool to the HTML editor if it was added to the custom options JSON

HTML editor tools can be added by adding them to the custom options JSON

---

Api/Core/Queries/WiserInstallation/CreateTablesConfigurator.sql

remove "extra" commas from CreateTablesConfigurator script

---

FrontEnd/Core/Scripts/shared/users.service.js

solve bug were the adminlogin value would be overwritten with false since adminlogin is not present in token information

solve bug were the adminlogin value would be overwritten

---

Api/Modules/Items/FieldTemplates/HTMLeditor.js
FrontEnd/Modules/Base/Scripts/Utils.js
FrontEnd/Modules/Dashboard/Scripts/Dashboard.js

fixed wrong string method used to get the file extension
also removed some unrelated debug console.logs
---
- https://app.asana.com/0/0/1206476089265280

Fixed HTML Editor Insert Image adding filename twice

---

Api/Modules/Queries/Services/StyledOutputService.cs

asana: https://app.asana.com/0/1199894242406919/1206876126573701/f

Add "isMainBranch" parameter to styled output api

---

Api/Modules/Templates/Services/TemplatesService.cs

Updated entity displayName to include both friendly name and internal name
---
- https://app.asana.com/0/0/1206784521734580

Entity list dropdown now always shows both entity name and friendly name 

---

Api/Core/Models/ApiSettings.cs
Api/Modules/Branches/Models/Constants.cs
Api/Modules/Branches/Services/BranchesService.cs
Api/Modules/Grids/Services/GridsService.cs
FrontEnd/Core/Scripts/main.js
FrontEnd/Core/Scripts/store/index.js
FrontEnd/Core/Views/Home/Index.cshtml

* Added support for styled output.
* Removed HTML element that was accidentically left after debugging.
* Increased timeouts for some queries.
Asana ticket: https://app.asana.com/0/1205090868730163/1206889828993331

Some improvements to branches

---

Api/Modules/Modules/Services/ModulesService.cs

https://app.asana.com/0/1199894242406919/1206544323178367/f

add WiserParentUpdates to table list

---

FrontEnd/Modules/Dashboard/Scripts/Dashboard.js

asana : https://app.asana.com/0/1201027711166952/1206693903878262/f

enable resizable property for dashboard grid

---

FrontEnd/Modules/DynamicItems/Scripts/Fields.js

Added the linkType to the data that a field will send to the API on update, so the API knows where to store the data
Saved item details on Fetim platform. Didn't work before the change, did afterwards (needs the bugfix in the GCL as well!)
GCL bugfix for same issue
https://github.com/happy-geeks/geeks-core-library/pull/550
https://app.asana.com/0/1205727761850957/1206657052949247

Field data send to API needs to include linkType

---

Api/Core/Queries/WiserInstallation/CreateDedicatedItemTablesTriggers.sql
Api/Core/Queries/WiserInstallation/CreateTriggers.sql

solve issue with the update parent service receiving a update when no actual changes were done during the update trigger
This was done after we found a huge amount of items changes, the updates for item links and files were not checked against actual changes, the update trigger fires anyway causing this issue.
we tested this on iteration 4 of intergamma to see if the problem was gone and it was
none
https://app.asana.com/0/1199894242406919/1207065815657941/f

solve issue with the update parent service receiving a update

---

Api/Core/Queries/WiserInstallation/CreateTables.sql
Api/Modules/Queries/Models/StyledOutputModel.cs
Api/Modules/Queries/Models/StyledOutputOptionModel.cs
Api/Modules/Queries/Services/StyledOutputService.cs

ran it locally and placed a breakpoint to check if items were parsed correctly
- Not yet, I noticed the documentation for the whole of styled output seems to be missing, i made a asana ticket to fix this. (https://app.asana.com/0/0/1207315474180775/f )
none
https://app.asana.com/0/1201027711166952/1207258858022215/f

add options field support to styled output service

---

Api/Core/Queries/WiserInstallation/CreateDedicatedItemTablesTriggers.sql
Api/Core/Queries/WiserInstallation/CreateTriggers.sql

selected a few lines, pressed the delete button
- [ x Bug fix (non-breaking change which fixes an issue)
checked the query in navicat
https://app.asana.com/0/1205090868730163/1207110900958952/f

remove unused variable

---

.github/workflows/publish-new-release-ext-2-live.yml

Change the secrets base directory on deployment to external server 2, because on external server 2 everything is installed on the D-drive. 
By running these changes in another repository and validating the deployment.
-
https://app.asana.com/0/1206035396570868/1206931088376411

Change setting on deployment

---

Api/Api.csproj
Api/Modules/Queries/Services/StyledOutputService.cs
FrontEnd/FrontEnd.csproj
Wiser.Tests/Wiser.Tests.csproj

Improve the styled output service
Serveral refactors and fix issue with options being deserialized when null or empty.
Tested by locally running Wiser and calling the API to check if the correct resultst are given and the flow takes the correct paths.
N/A
https://app.asana.com/0/1201027711166952/1207258858022215/f

Improve the styled output service

---

Api/Core/Queries/WiserInstallation/CreateDedicatedItemTablesTriggers.sql
Api/Core/Queries/WiserInstallation/CreateTriggers.sql

this was not tested, since its just TRUE to FALSE  
- [ x I have reviewed and tested my changes
- [ x I have commented my code, particularly in hard-to-understand areas
- [ x I have made corresponding changes to the documentation
Add any open pull requests from other projects that are related to this pull request that should be merged along with this one. If there are none, you can simply say "none" or "N/A", or just leave this section empty.
Add a link to the Asana ticket. Note that **_ONLY_** the URL should be added, not the name of the ticket!

turn the parent update off in wiser triggers by default

---

Api/Core/Queries/WiserInstallation/CreateTriggers.sql
Api/Modules/Modules/Services/ModulesService.cs

Remove the wiser_itemlink part of the 'ItemDelete' trigger on 'wiser_item'
Because this trigger could remove links between items that are not in the wiser_item table but have their own prefix table.
Removing this part of the trigger does result in dirty links being left in wiser_itemlink, which need to be cleaned in another way.
It was not. There is no new code to test.
none
https://app.asana.com/0/1205090868730163/1207412788338893

Removed dangerous trigger

---

FrontEnd/Core/Models/FrontEndSettings.cs
FrontEnd/Core/Scripts/main.js
FrontEnd/Core/Views/Home/Index.cshtml
FrontEnd/Modules/Configuration/Views/Configuration/Index.cshtml
FrontEnd/Modules/ContentBox/Views/ContentBox/Index.cshtml
FrontEnd/Modules/ContentBuilder/Views/ContentBuilder/Index.cshtml

Removed all references to MarkerIO
Removed the Report Bug menu options
Local run to see if menu options are gone.
none
https://app.asana.com/0/1205090868730163/1206419348276791

Removed all MarkerIo uses and the Report Bug option

---

Api/Api.csproj
Api/Core/Services/ClientDatabaseConnection.cs
Api/Modules/Branches/Services/BranchesService.cs
Api/Modules/Templates/Interfaces/DataLayer/IDynamicContentDataService.cs
Api/Modules/Templates/Interfaces/DataLayer/ITemplateDataService.cs
Api/Modules/Templates/Interfaces/IDynamicContentService.cs
Api/Modules/Templates/Interfaces/ITemplatesService.cs
Api/Modules/Templates/Services/CachedTemplatesService.cs
Api/Modules/Templates/Services/DataLayer/DynamicContentDataService.cs
Api/Modules/Templates/Services/DataLayer/TemplateDataService.cs
Api/Modules/Templates/Services/DynamicContentService.cs
Api/Modules/Templates/Services/TemplatesService.cs
Api/Modules/Tenants/Helpers/TenantHelpers.cs
Api/Startup.cs
FrontEnd/Core/Scripts/main.js
FrontEnd/Core/Scripts/shared/branches.service.js
FrontEnd/Core/Views/Home/Index.cshtml
FrontEnd/FrontEnd.csproj
Wiser.Tests/Wiser.Tests.csproj

The branches functionality of Wiser was originally only made to work if both the branch and the production database are on the same SQL server. This PR changes that so that it also works if they are on different servers.
I did a lot of tests with making and merging branches and deploying templates and components to branches.
https://github.com/happy-geeks/wiser-task-scheduler/pull/201
https://app.asana.com/0/1205090868730163/1206931088376427

Branches for multiple database servers

---

Api/Modules/Queries/Models/StyledOutputOptionModel.cs
Api/Modules/Queries/Services/StyledOutputService.cs

added timing logging to the styled output service for profiling
locally and connecting to the intergamma database
Please describe how you tested your changes and how you confirmed this functionality is not a breaking change.
(there has been a pr for adding the new columns at the geekcorelib, this has been merged already)
https://app.asana.com/0/1204371236183532/1206473300071322/f

add timing logic for styled output

---

Api/Modules/Queries/Services/StyledOutputService.cs

I ran this locally and ran the main query for one of our costumers
this takes 10 minutes normally, with the cache in it this is 5min
none
https://app.asana.com/0/1199894242406919/1207511417583256/f

add caching to styled output service

---

Api/Modules/Items/FieldTemplates/image-upload.js
FrontEnd/Modules/Admin/Scripts/EntityTab.js
FrontEnd/Modules/FileManager/Scripts/FileManager.js

Added support for tiff images. This does nothing more than add it to the default allowed file extensions for image uploads.
I tested this by checking if I can upload tiff files without errors.
https://github.com/happy-geeks/geeks-core-library/pull/614
CON-261

Added support for tiff images

---

Api/Core/Queries/WiserInstallation/CreateDedicatedItemTablesTriggers.sql
Api/Core/Queries/WiserInstallation/CreateTables.sql
Api/Core/Queries/WiserInstallation/CreateTriggers.sql
Api/Modules/Grids/Services/GridsService.cs
Api/Modules/Modules/Services/ModulesService.cs

Updated triggers for `wiser_itemdetail` tables. This is needed for being able to properly merge changes that are done in `wiser_itemdetail` tables when merging a Wiser branch. Some changes, such as changes to `language_code` and `key`, were never merged.
I tested this by making several test branches in the wiser demo database and doing lots of test merges there.
https://github.com/happy-geeks/geeks-core-library/pull/616
https://github.com/happy-geeks/wiser-task-scheduler/pull/222
https://app.asana.com/0/1205090868730163/1207370849820110

Updated triggers to also log changes to key, language_code etc of wiser_itemdetail

---

Api/Modules/EntityTypes/Controllers/EntityTypesController.cs
Api/Modules/EntityTypes/Interfaces/IEntityTypesService.cs
Api/Modules/EntityTypes/Services/EntityTypesService.cs
FrontEnd/Core/Scripts/main.js
FrontEnd/Core/Scripts/shared/branches.service.js
FrontEnd/Core/Scripts/store/index.js

When getting a list with all entities for merging a branch, we will now get the entities from the branch database instead of production. This fixes the problem that if a new entity has been created in a branch, that it couldn't be merged to production.
By checking if the code for getting entities actually gets them from the correct database.
N/A
No asana ticket.

Get entities from selected branch

---

Api/Modules/Queries/Controllers/StyledOutputController.cs
Api/Modules/Queries/Interfaces/IStyledOutputService.cs
Api/Modules/Queries/Services/StyledOutputService.cs

because we are going to change the styled output table to use auto increment for its ids we added the function to use the name instead to find styled outputs
ran locally with postman
note: i made a task to remind me to update the documentation once this is in
Jira

create new end point for accessing styled outputs by name

---

Api/Core/Queries/WiserInstallation/CreateTables.sql
Api/Modules/Permissions/Controllers/PermissionsController.cs
Api/Modules/Permissions/Enums/PermissionSubjects.cs
Api/Modules/Permissions/Interfaces/IPermissionsService.cs
Api/Modules/Permissions/Models/EndpointPermissionsData.cs
Api/Modules/Permissions/Models/PermissionData.cs
Api/Modules/Permissions/Models/PermissionUpdateModel.cs
Api/Modules/Permissions/Services/PermissionsService.cs
FrontEnd/Modules/Admin/Scripts/RoleTab.js
FrontEnd/Modules/Admin/Views/Admin/Index.cshtml

Added functionality to manage endpoint permissions via the admin module. These permissions were already added to the GC a while ago, but couldn't be managed in Wiser yet. WIth this, we can set permissions per role per endpoint on an API or other application.
By adding, updating and removing permissions in the admin module.
N/A
https://app.asana.com/0/1205727761850957/1206193274458372

Endpoint permissions

---

Api/Modules/Queries/Services/QueriesService.cs

we cant use that kind of init (yet) changes to to the old way
i checked if it compiled
none
none

change code so it can run on older dotnets

---

Api/Modules/Items/FieldTemplates/sub-entities-grid.html

Bugfix "refresh" dependency action not working on sub-entities-grid
Added a combobox and sub-entities-grid to Wiser demo environment and made them dependant on each other. When changing the combobox, the sub-entities-grid was not reloaded. After making the change, the problem was solved.
https://app.asana.com/0/1201027711166952/1206320932615542

Fixed dependency action "refresh" not working on sub-entiteis-grid

---

Api/Modules/Templates/Services/DataLayer/TemplateDataService.cs

When deploying a JavaScript template to a branch the external files are now correctly moved to the branch.
Tested by deploying a template with and without external file to a branch to check if it is correctly linked.
N/A
https://app.asana.com/0/1205090868730163/1207716522003083

Fix external files not being deployed to the branch.

---

Api/Modules/Grids/Services/GridsService.cs
Api/Modules/Kendo/Models/AttributesModel.cs
Api/Modules/Kendo/Models/GridColumn.cs
FrontEnd/Modules/Dashboard/Scripts/Dashboard.js
FrontEnd/Modules/DynamicItems/Css/DynamicItems.css
FrontEnd/Modules/DynamicItems/Scripts/DynamicItems.js

Add double click to old and new value of history changes of an item to see the full change.
Includes fix for same functionality in the dashboard WTS logs.
Tested by double clicking on both the old and new value and see if both are toggled.
N/A
https://app.asana.com/0/1201027711166952/1203702191418792

Add option to unfold changes of an item

---

Api/Modules/VersionControl/Models/CommitModel.cs
FrontEnd/Modules/VersionControl/Scripts/VersionControl.js

Added a column to Template version control Deploy tab to quickly see the status of any review requests if there are any.
wiserdemo has some templates ready to deploy that have reviews with different status
https://app.asana.com/0/1205090868730163/1206957799611470

Added "Review" column to template version control Deploy tab

---

FrontEnd/Modules/DynamicItems/Scripts/Fields.js

Send value of changed property to backend when refreshing component via dependency
Made an environment with the dependency action "refresh" without this change. The new value of the changed property was not available in the query in the backend. Used successfully the new value in the backend query after this change.
N/A
N/A

Send value of changed property to backend when refreshing component via dependency

---

Api/Modules/Templates/Controllers/TemplatesController.cs
Api/Modules/Templates/Services/TemplatesService.cs

Ensure the endpoint for the entire trree view, used by the WTS, always returns the error.
Tested by forcing an error to see if the flow is handled correctly and checked if the normal flow still works as expected.
https://github.com/happy-geeks/wiser-task-scheduler/pull/235
https://app.asana.com/0/7257459017111/1207193040742570

Ensure error message is exposed

---

Api/Modules/Files/Services/FilesService.cs

Bugfix removing files without content_url. Remove a file without a content_url didn't work.
Removing file didn't work. After change the file is successfully removed.
- [ X I have commented my code, particularly in hard-to-understand areas
N/A
N/A

Bugfix removing file when content_url is empty

---

FrontEnd/Modules/Templates/Scripts/DynamicContent.js

In a dynamic content window. if you clicked on the save and close button and the save wasn't succesful it would close the window anyway.  This could mean losing a lot of progress as the item and the changed you made weren't saved.
The change is adding a boolean return value to the save function indicating whether the save was succesful. Then in the event handler of the save and close button I check for the return value to determine whether the window should be closed.
Because I was making a change in the save function anyway I also fixed some wrong indenting that made the function more difficult to read.
Created a new item, tested the unhappy flow by not filling in a name before clicking on the save and close button then filled in a name to test the happy …

Don't close content window when saving failed

---

Api/Modules/Templates/Services/TemplatesService.cs

Changed to support databases that only allowed single quotes.
Tested by checking if the query gives results.
N/A
N/A

Change double quotes to single quotes

---

FrontEnd/Modules/DynamicItems/Views/DynamicItems/Index.cshtml

Add explanation to the checkbox to create item on main branch
Tested by checking if the explanation is visible when creating an item on a branch and that it is not visible when creating an item on the main branch.
N/A
https://app.asana.com/0/1205090868730163/1208361137839856

Add explanation to the checkbox to create item on main branch

---

Api/Api.csproj
Api/Core/Queries/WiserInstallation/CreateTriggers.sql
Api/Modules/Branches/Services/BranchesService.cs
FrontEnd/Core/Scripts/main.js
FrontEnd/Core/Scripts/store/index.js
FrontEnd/FrontEnd.csproj
Wiser.Tests/Wiser.Tests.csproj

Added objects from the `easy_objects` table to the settings to be merged.
Tested to see if the JSON output now includes the `EasyObjects` type, which the WTS can then use to perform the actual merging.
N/A
CON-356

Branch merge easy objects

---

FrontEnd/Core/Scripts/shared/modules.service.js
FrontEnd/Modules/FileManager/Controllers/FileManagerController.cs
FrontEnd/Modules/FileManager/Css/FileManager.css
FrontEnd/Modules/FileManager/Models/FileManagerViewModel.cs
FrontEnd/Modules/FileManager/Views/FileManager/Index.cshtml
FrontEnd/package-lock.json

Added a query string variable to iframe url in order to hide elements in the right pane when the FileManager module is opened directly. The fields can't be edited, and don't contain helpful data. 
This was tested by checking to see if the FileManager module works as intended, and other parts of Wiser stay functional. 
N/A
https://app.asana.com/0/1201027711166952/1207999173733425

Initial commit

---

Api/Modules/Items/FieldTemplates/sub-entities-grid.js
FrontEnd/Modules/DynamicItems/Scripts/Grids.js
FrontEnd/Modules/DynamicItems/Scripts/Windows.js

Fixed bug when linking items with sub-entities-grid and current item is source. The wrong entity type was sent to the Wiser API. The Wiser API then did not create a link.
Tried to create a link without this fix. The link is not created. Tried again after making the changes. Link has been created.
N/A
https://app.asana.com/0/1201027711166952/1206120608401144

Bugfix in linking items when current item is source

---

Api/Modules/Files/Controllers/FilesController.cs
Api/Modules/Items/Controllers/ItemsController.cs
FrontEnd/Modules/FileManager/Scripts/FileManager.js

Fixed some small issues where parameters were changed wrongly. Also added type checks to routes.
By using the corresponding functionality and checking if it works correctly again. 
N/A
No Asana ticket, came across these issues when working on something unrelated.

Fixed some bugs caused by encrypted id refactoring

---

Api/Core/Queries/WiserInstallation/CreateTables.sql
Api/Modules/Templates/Helpers/TemplateHelpers.cs
Api/Modules/Templates/Models/Template/TemplateSettingsModel.cs
Api/Modules/Templates/Services/DataLayer/HistoryDataService.cs
Api/Modules/Templates/Services/DataLayer/TemplateDataService.cs
Api/Modules/Templates/Services/HistoryService.cs
FrontEnd/Modules/Templates/Views/Templates/Partials/HtmlSettings.cshtml

adding 2 checkboxes to the tempalte module to more easily set robots noindex,nofollow tags, these can still be overwritten if someone sets a preload query that fills these values as well 
tested by trying it on wiser demo, changed settings back and forth and made sure teh query approach still takes presidency
https://github.com/happy-geeks/geeks-core-library/pull/719
Add a link to the Asana ticket. Note that **_ONLY_** the URL should be added, not the name of the ticket!

add robots no index and no follow tags to templates

---

Api/Api.csproj
Api/Modules/Pdfs/Services/PdfsService.cs
Api/Startup.cs

New version of Evo PDF.
Tested this with a customer that uses the PDF functionality.
https://github.com/happy-geeks/geeks-core-library/pull/714
https://app.asana.com/0/1200346761113317/1207757339323491

Evopdf version

---

Api/Modules/Items/FieldTemplates/HTMLeditor.js

perform javascript improvements/cleanup in HTMLeditor.js

---

Api/Modules/Items/FieldTemplates/iframe.js

perform javascript improvements/cleanup in Iframe.js

---

Api/Modules/Items/FieldTemplates/input.js

perform javascript improvements/cleanup in Input.js

---

Api/Modules/Items/FieldTemplates/file-upload.js

perform javascript improvements/cleanup in file-upload.js

---

Api/Modules/Items/FieldTemplates/multiselect.js

perform javascript improvements/cleanup in multiselect.js

---

Api/Modules/Items/FieldTemplates/image-upload.js

perform javascript improvements/cleanup in ImageUpload.js

---

Api/Modules/Items/FieldTemplates/item-linker.js

perform javascript improvements/cleanup in item-linker.js

---

Api/Api.csproj
Api/Core/Services/ClientDatabaseConnection.cs
Api/Modules/Items/FieldTemplates/image-upload.js
FrontEnd/FrontEnd.csproj
Wiser.Tests/Wiser.Tests.csproj

Fix the URL that is used to upload an image to the API. Also updated packages and fixed other code to compile project.
Tested by running the project locally and uploading an image.
N/A
N/A

Fix image upload

---

Api/Modules/Items/FieldTemplates/qr.js

perform javascript improvements/cleanup in qr.js

---

Api/Core/Queries/WiserInstallation/BranchSettingsModule.sql
FrontEnd/Core/Views/Home/Index.cshtml

Fixed module opening after new identity framework and ensured Branch module is initially added to the table changes table to prevent problems with migrations.
Tested by creating a new Wiser 3 customer.
<md-block>
1. If there is already a "log-item" section without a version number at the top, add new `li` like the others to it and describe your changes in a costumer friendly way (so not too technical).
1. If there is no log-item at the top yet without a complete version number add it and add your `li` item there, (you can copy paste it from the comments a few lines above the update-log section). …

Fix flow to create new Wiser 3 customer

---

Api/Modules/EntityTypes/Models/EntityTypeModel.cs
Api/Modules/EntityTypes/Services/EntityTypesService.cs
FrontEnd/Modules/DynamicItems/Scripts/Dialogs.js

When creating an item in the tree view it would always create the link under link type number `1`.
Now the link type numbers of the entities are provided for the dialog to provide the correct link type between both entities when creating the new child item.
Tested by creating an item on a different link number than `1` to check if it is created with the correct link type number as configured in `wiser_link`. Also tested creating other items that are created with link type number `1` and use parent ID.
<md-block>
1. If there is already a "log-item" section without a version number at the top, add new …

Use the correct link type number

---

Api/Modules/Items/FieldTemplates/radiobutton.js

perform javascript improvements/cleanup in radiobutton

---

FrontEnd/Modules/Dashboard/Views/Dashboard/Index.cshtml
FrontEnd/Modules/DynamicItems/Scripts/Grids.js

Kendo UI has an option `persistSelection` that allows the  selection to be kept when filtering, sorting or paging in a Grid. This change allows this to work for grids that are created as parameter for an actionbutton.
Set `persistSelection` in de options, opened a grid and used the filter functionality to see if the selection was persisted.
<md-block>
1. If there is already a "log-item" section without a version number at the top, add new `li` like the others to it and describe your changes in a costumer friendly way (so not too technical).
1. If there is no log-item at the top yet without a complete …

Add persist selection option for grids.

---

Api/Core/Queries/WiserInstallation/CreateTables.sql
Api/Core/Queries/WiserInstallation/CreateTriggers.sql
Api/Modules/EntityTypes/Services/EntityTypesService.cs
FrontEnd/Modules/Admin/Scripts/EntityModel.js
FrontEnd/Modules/Admin/Scripts/EntityTab.js
FrontEnd/Modules/Admin/Views/Admin/Index.cshtml
FrontEnd/Modules/DynamicItems/Scripts/Dialogs.js

to prevent items from being made on the main branch when this really should not be done i added a setting for entities
(this will for example be used for "promotions" that currently ask you if you want to create it on the main branch as well, which should never be done)
i ran it locally and abused the `horren` environment to test it 
https://github.com/happy-geeks/geeks-core-library/pull/767
CON-1075

add AllowCreationOnMainFromBranch to EntityModel

---

Api/Modules/Items/FieldTemplates/multiselect.html
Api/Modules/Items/Services/ItemsService.cs

A combobox that saves its value as a link on a link type that has "UseItemParentId" enabled would not retrieve its value properly. This is now fixed.
In addition, setting "currentItemIsDestinationId" to true for a multiselect in conjunction with "UseItemParentId" is now an invalid combination and will show an error.
Used a debug build and tested the changes in a sandbox environment, confirming that the changes work as expected.
<md-block>
1. If there is already a "log-item" section without a version number at the top, add new `li` like the others to it and describe your changes in a costumer friendly way (so not too technical).
1. …

Fixed some parent ID issues

---

Api/Core/Queries/WiserInstallation/CreateTriggers.sql

The triggers for the `wiser_permission` table didn't log changes in `wiser_history` for 4 columns. These columns have been added to all three triggers (`INSERT`, `UPDATE`, `DELETE`).
The columns added were:
- `query_id`
- `data_selector_id`
- `endpoint_url`
- `endpoint_http_method`
Replaced the triggers for `wiser_permission` in a sandbox environment, and tested the `INSERT`, `UPDATE` and `DELETE` triggers and checked if the entries in `wiser_history` were correct.
<md-block>
1. If there is already a "log-item" section without a version number at the top, add new `li` like the others to it and describe your changes in a costumer …

Updated triggers for `wiser_permission`

---

Api/Modules/Items/FieldTemplates/sub-entities-grid.js

Fixed wrong entity type being passed when editing directly from a grid.
Used a debug build of Wiser to test the changes and confirmed that editing in the in-cell editing mode of the grid can now properly update the property.
<md-block>
1. If there is already a "log-item" section without a version number at the top, add new `li` like the others to it and describe your changes in a costumer friendly way (so not too technical).
1. If there is no log-item at the top yet without a complete version number add it and add your `li` item there, (you can copy paste it from the comments a few lines above the update-log section).
</md-block> …

In cell grid editing fix

---

Api/Modules/Items/FieldTemplates/secure-input.js

refactor javascript for secure-input

---

Api/Modules/Items/FieldTemplates/linked-item.js

updated the itemn link js, just like with the other files im making these prs per file to keep it from turning to big
tested it on playground, the product has a itemlink item this behaved the same as with and without my changes

perform javascript fixes on linked-item.js

---

Api/Modules/Items/FieldTemplates/scheduler.js

updated the itemn shedulerjs, just like with the other files im making these prs per file to keep it from turning to big
tested it on playground,added a sheduler to a product and tested if it still loaded, it did, could also switch tabs.

refactor javascript for scheduler

---

Api/Modules/Items/FieldTemplates/timeline.js

updated the timeline js, just like with the other files im making these prs per file to keep it from turning to big
tested it on wiserdemo, modified a item to have a timeline and looked it it behaved the same.

refactor javascript for timeline

---

Api/Modules/Items/FieldTemplates/textbox.js

updated the textbox js, just like with the other files im making these prs per file to keep it from turning to big
tested it on wiserdemo, looked at various textboxes to see if they still behaved the same

refactor javascript for textbox

---

Api/Modules/Grids/Services/GridsService.cs

Get the correct language code value to show in the sub-entities-grid overview and allow multiple language codes of the same details to be shown.
Tested if the correct value of a detail with language code is shown in the overview. Done this with 2 language codes separately and at the same time. Also tested a detail without language code to check if those still work correctly.
N/A
https://app.asana.com/1/5038780173035/project/1205090868730163/task/1207481127021886

Use language code for details in sub-entities-grid overview

---

Api/Modules/VersionControl/Services/DataLayer/ReviewDataService.cs

Add check to prevent duplicate comments in version control review.
I tested it locally using a demo project. At first, I noticed duplicate comments, but after making the changes, the duplicate comments were gone.
none
https://app.asana.com/1/5038780173035/project/1205090868730163/task/1207302241913561

Add check to prevent duplicate comments in version control review

---

Api/Modules/Products/Services/ProductsService.cs

there were a few issues with the new products api regarding the creation of default settings on existing projects and issues with both parsing styled output and storing its results, including a mistake that caused mysql injection, these are resolved now
tested on the IG ACC environment
- [] I have made corresponding changes to the documentation
none
none

solve issues with productsapi

---

Api/Modules/EntityProperties/Services/EntityPropertiesService.cs
Api/Modules/Grids/Services/GridsService.cs

This is a test PR to see if the new CODEOWNERS file works. That file should make it so that this PR will request a review to the .NET team automatically.

Fixed problem with grids and admin module.

---

Api/Core/Queries/WiserInstallation/CreateDedicatedItemTablesTriggers.sql
Api/Core/Queries/WiserInstallation/CreateDedicatedLinkTableTriggers.sql
Api/Core/Queries/WiserInstallation/CreateTriggers.sql
Api/Core/Services/WiserDatabaseHelpersService.cs

Triggers were case-insensitive before, which meant that if someone changes the casing and nothing else, that change would not show up in `wiser_history`. This has been fixed in this PR. 
Tested on WIser demo.
N/A
https://app.asana.com/1/5038780173035/project/1200346761113317/task/1210170313922977

Updated all triggers so that they are case-sensitive

---

Api/Modules/Branches/Services/BranchesService.cs

Refactored `BranchesService` to make it more readable:
* Moved all inline functions to normal class functions.
* Changed most calls of `dictionary.ContainsKey()` to `dictionary.TryGetValue()`.
* Some other minor code improvements.
Also fixed a bug that caused exceptions when checking for conflicts while the branch contains deleted item links.
Tested in Wiser demo.
N/A
https://app.asana.com/1/5038780173035/project/1205090868730163/task/1208547881514932

Refactored `BranchesService` to make it more readable

---

Api/Api.csproj
Api/Modules/Queries/Services/StyledOutputService.cs

I pulled,
I compiled
i failed
I fixed
I compile again
witness me!
i pressed build
nobody but us chickens
noooooooo ticket here

solve mistake that causes compile error

---

Api/Core/Queries/WiserInstallation/CreateTables.sql
Api/Modules/EntityProperties/Services/EntityPropertiesService.cs

Found an issue testing the new feature on a customer environment I had not been before. I forgot to update the inputtype enum and that the group_id is now NOT NULL so the query need to do a 0 check, not a NULL check.
Please describe how you tested your changes and how you confirmed this functionality is not a breaking change.
n/a
n/a

Small bug fix for property groups feature

---

Api/Modules/Products/Services/ProductsService.cs

there was a issue with the product api out of date function when no date was provided, also optimized the product retrieval by putting it in a subqeury instead 
connected locally and used postman 
- [] I added new unit tests for my changes if applicable

solve a issue with the product api out-of-date function
